<?
// $sprachbasisdatei = "/home/praktikanten/mypassword.phtml";
ob_start();
if(!isset($praktdbslave)) {
	require("/home/praktika/etc/gb_config.inc.php");
}

if (!isset($_SESSION['s_loggedin']) || $_SESSION['s_loggedin'] == false) {
	header('Location: http://'.$_SERVER['HTTP_HOST'].'/login');
}

$_SESSION['restricted'] = RESTRICTED_COMPANY;
$_SESSION['current_user_group'] = USER_GROUP_COMPANIES;

// pageheader(array('page_title' => '&Auml;nderung Ihres Passwortes'));
# $_SESSION["s_firmenproparray"]["lastPage"] = "bearbeiter/newPassword";
if(!empty($_POST['save'])) {
	if(empty($_SESSION['s_loginid'])) die("noid");

	# echo $_POST["po"];
	$sql = "SELECT id FROM prakt2.bearbeiter WHERE passwort_plain = '".mysql_real_escape_string($_POST['po'])."' AND id = ".intval($_SESSION['s_loginid']);
	$result = $hDB->query($sql, $praktdbslave);
	
	if(mysql_num_rows($result) == 0) die("wrongpass");

	$sql = "INSERT INTO prakt2_temp.log SET value = 'Password changed (".md5($_POST["p"]).")', tid='b".intval($_SESSION['s_loginid'])."', ip = '".$_SERVER["REMOTE_ADDR"]."'";
	$hDB->query($sql, $praktdbmaster);
	
	$sql = "UPDATE bearbeiter SET passwort = OLD_PASSWORD('".mysql_real_escape_string($_POST['p'])."'), passwort_plain = '".mysql_real_escape_string($_POST['p'])."', modify=NOW() WHERE id = ".intval($_SESSION['s_loginid']);
	$hDB->query($sql, $praktdbmaster);

	echo "ok";
	exit();
}
?>
<div id="ajaxlogin" style="padding:20px;padding-top:9px; width:400px;">
    <p>
        Um Missbrauch vorzubeugen, geben Sie bitte Ihr <b>altes Passwort</b><br /> zur Authentifizierung an.<br />
        Danach k&ouml;nnen Sie Ihr neues Passwort frei w&auml;hlen.<br /><br />
    </p>
    <style type="text/css">
        div#ajaxlogin label#pwd_old_label,
        div#ajaxlogin label#pwd1_label,
        div#ajaxlogin label#pwd2_label {
            width:150px;
        }
        div#ajaxlogin input#pwd_old,
        div#ajaxlogin input#pwd1,
        div#ajaxlogin input#pwd2{
            width:200px;
        }
    </style>
	<form method="POST" action="#" style="text-align:center;">
	<fieldset>
		<p>
			<label for="pwd_old" id="pwd_old_label">altes Passwort</label>
				<input type="password" id="pwd_old" name="passwort_old" maxlength="35" value="" />
		</p>
		<br />
		<p>
			<label for="pwd1" id="pwd1_label">neues Passwort</label>
				<input type="password" id="pwd1" name="passwort1" maxlength="35" value="" />
		</p>
		<p>
			<label for="pwd2" id="pwd2_label">Passwortwiederholung</label>
				<input type="password" id="pwd2" name="passwort2" maxlength="35" value="" />
		</p>
	</fieldset>
	</form>
	<p id="tmp_result" style="display:none;" class="error"></p>
</div>
<fieldset class="login_control_panel smallbox_footer" style="border:0px solid #fff !important; text-align:center;">
    <p>

		<a class="button red small" style="float:none;" onclick="smallbox.hide(false); return false;" value="Login">Abbrechen</a>
        <a class="button green small" style="float:none;" onclick="changePassword(); return false;" value="Login">Speichern</a>

    </p>
</fieldset>
<script type="text/javascript">
	function changePassword() {
		$('#tmp_result').css("display", "none");
		if($('#pwd_old').val() == '') {
			$('#pwd_old_label').attr("class", "error");

			$('#tmp_result').innerHTML = "Bitte geben Sie ihr altes Passwort an!";
			$('#tmp_result').css("display", "");
			return;
		} else {
			$('#pwd_old_label').className = '';
		}

		if($('#pwd1').val() == '') {
			$('#pwd1_label').attr("class", "error");

			$('#tmp_result').html("Bitte geben Sie ein neues Passwort an!");
			$('#tmp_result').css("display", "");
			return;
		} else {
			$('#pwd1_label').attr("class", "");
		}

		if($('#pwd1').val().length < 4) {
			$('#pwd1_label').attr("class", "error");

			$('#tmp_result').html("Das Passwort muss mindestens 4 Zeichen lang sein!");
			$('#tmp_result').css("display", "");
			return;
		} else {
			$('#pwd1_label').attr("class", "");
		}

		if($('#pwd2').val() == '') {
			$('#pwd1_label').attr("class", "error");

			$('#tmp_result').html("Bitte wiederholen Sie Ihr Passwort!");
			$('#tmp_result').css("display", "");
			return;
		} else {
			$('#pwd2_label').attr("class", "");
		}

		if($('#pwd2').val() != $('#pwd1').val()) {
			$('#pwd2_label').attr("class", "error");

			$('#tmp_result').html("Beide neuen Passw&ouml;rter stimmen nicht &uuml;berein!");
			$('#tmp_result').css("display", "");
			return;
		} else {
			$('#pwd2_label').attr("class", "");
		}

		$.post("/home/firmen/bcenter/bearbeiter/newPassword.phtml", "p=" + $('#pwd2').val() + "&po=" + $('#pwd_old').val() + "&save=true", function(e) {
			if(e == "wrongpass") {
				$('#pwd_old_label').attr("class", "error");

				$('#tmp_result').html("Ihr altes Passwort ist nicht korrekt!");
				$('#tmp_result').css("display", "");
			
				return;
			}
			if(e=="ok") {
				smallbox.hide(true);
			} else {
				smallbox.hide('error');
			}
		});
	}
</script>