<?php
require("/home/praktika/etc/config.inc.php"); 

$_SESSION['sidebar'] = "none";
$_SESSION['current_user_group'] = USER_GROUP_COMPANIES;

if (!empty($_POST['email'])) { 
	$fertig = 1;

	if ( isset($_POST['email']) && !empty($_POST['email']) ) {
		$validtext = Praktika_Validate::validateMail($_POST['email']);
	} else {
		$fertig = 0;
	}

	if ( empty($validtext[0]) ) {
		$fertig = 0;
	}

	if ( substr_count($_POST['email'], '@praktika.de') ){
		$fertig = 0;
	}

	if ($fertig == 0) {
		pageheader( array('page_title' => '&Uuml;berpr&uuml;fung ihrer eMail - Adresse') );
		
		echo '<p class="hint error">Bitte pr&uuml;fen Sie Ihre E-Mail Adresse auf Fehler.<br /><br />Folgende E-Mail Adresse konnte nicht verifiziert werden: '.htmlentities($_POST['email']).'</p>'."\n";
		echo '<p class="control"><a href="/neuanmeldung/check_company/" class="button small">zur&uuml;ck</a></p>'."\n";
	} else {
		// existiert bearbeiter?
		$sql = sprintf("SELECT 
							id, 
							email, 
							inactive, 
							vname, 
							name 
						FROM 
							".$database_db.".bearbeiter 
						WHERE 
							email = '%1\$s'",
						$_POST['email']);

		$rs = $hDB->query($sql, $praktdbslave);
		$num_bearbeiter = mysql_num_rows($rs);
		$bearbeiter = mysql_fetch_array($rs);
		
		// existiert nutzer?
		$sql = sprintf("SELECT 
							id, 
							email, 
							inactive 
						FROM 
							".$database_db.".nutzer 
						WHERE 
							email = '%1\$s'",
						$_POST['email']);
		$rs = $hDB->query($sql, $praktdbslave);
		$num_nutzer = mysql_num_rows($rs);
		$nutzer = mysql_fetch_array($rs);		
		
		// existiert firma?
		$sql = sprintf("SELECT 
							id, 
							email, 
							inactive 
						FROM 
							".$database_db.".firmen 
						WHERE 
							email = '%1\$s'",
						$_POST['email']);
		$rs = $hDB->query($sql, $praktdbslave);
		$num_firma = mysql_num_rows($rs);
		$firma = mysql_fetch_array($rs);
		
		// user gesperrt?
		$sql = sprintf("SELECT 
							email
						FROM 
							".$database_db.".emailblacklist 
						WHERE 
							email = '%1\$s'",
						$_POST['email']);
		$rs = $hDB->query($sql, $praktdbslave);
		$num_gesperrt = mysql_num_rows($rs);

		// existiert kein eintrag mit der e-mail-adresse und ist diese adressse nicht gesperrt?
		if ($num_bearbeiter == 0 && $num_nutzer == 0&& $num_firma == 0 && $num_gesperrt == 0) {
			header('Location: /neuanmeldung/company/'.$_POST['email']);
		} else {
			pageheader(array('page_title' => '&Uuml;berpr&uuml;fung ihrer eMail - Adresse'));

			// ist der user gesperrt?
			if ( ($bearbeiter['inactive'] == 'true' || $nutzer['inactive'] == 'true') && $num_gesperrt != 0) {
				echo '<p class="hint error">'.$language['strNutzergesperrt'].'</p>'."\n";
			} else {
				echo '<p class="hint error">Es existiert bereits ein Eintrag, welcher mit der von Ihnen eingegebenen eMail-Adresse <strong>'.htmlentities($_POST['email']).'</strong> &uuml;bereinstimmt.</p>'."\n";
				echo '<p class="hint info">Sie k&ouml;nnen sich nun mit dem hinterlegten Passwort <a href="/login/" onclick="smallbox.loadLogin(function(e) { location.href=\'/recruiting/\'; }); return false;">einloggen</a>.<br /><br />Falls Sie Ihr Passwort vergessen haben, lassen Sie sich einfach ein neues Passwort an die hinterlegte eMail-Adresse zusenden.</p>'."\n";
				echo '<p class="hint info">Nutzen Sie bitte eine alternative eMail-Adresse oder nehmen mit uns Kontakt auf : 0800-69772582.<br /><br />Vielen Dank f&uuml;r Ihr Verst&auml;ndnis.'."\n";
				
				if ($num_bearbeiter != 0) {
					echo '<ul>'."\n";
					echo '	<li>Eingetragener Bearbeiter: '.$bearbeiter['vname'].' '.$bearbeiter['name'].'</li>'."\n";
					echo '	<li><a href="/login/'.$bearbeiter['id'].'/" onclick="smallbox.loadLogin(function(e) { location.href=\'/recruiting/\'; }); return false;">Jetzt einloggen</a> und Account reaktivieren!</li>'."\n";
					echo '	<li><a href="/company/passwort_vergessen/'.$bearbeiter['id'].'/'.time().'/">Passwort zusenden</a></li>'."\n";
					echo '</ul>'."\n";
				} elseif ($num_nutzer != 0) {
					echo '<ul>'."\n";
					echo '	<li><a href="/login/'.$nutzer['id'].'/" onclick="smallbox.loadLogin(function(e) { location.href=\'/recruiting/\'; }); return false;">Jetzt einloggen</a> und Account reaktivieren!</li>'."\n";
					echo '	<li>Passwort vergessen? - <a href="/candidate/passwort_vergessen/'.$nutzer['id'].'/'.time().'/">Jetzt anfordern!</a></li>'."\n";
					echo '</ul>'."\n";
				}
				
				echo '<p class="control"><a href="/neuanmeldung/check_company/" class="button red small">zur&uuml;ck</a></p>'."\n";
			}
		}
	}
} else {
	pageheader(array('page_title' => 'Unternehmensdaten'));
	
	if (isset($_POST['email']) && empty($_POST['email'])) {
		echo '<p class="hint error">Bitte geben Sie Ihre eMail-Adresse ein.</p>'."\n";
	}
?>

<p>Bitte geben Sie Ihre eMail-Adresse an, die Sie f&uuml;r Bewerbungen und Mitteilungen nutzen m&ouml;chten. Das System pr&uuml;ft, ob Sie bereits bei praktika.de registriert sind.</p>
<form action="/neuanmeldung/check_company/" method="post" name="checkComapanyForm">
	<fieldset>
		<p>
			<label for="email">eMail-Adresse:</label>
			<input type="text" id="email" name="email" />
		</p>
	</fieldset>
	<fieldset class="control_panel">
		<p>
			<a href="#" class="button red small" onclick="document.checkComapanyForm.submit(); return false;">abschicken</a>
		</p>		
	</fieldset>
</form>
<br /><br />
<p class="hint info">Damit Sie alle eMails von praktika.de erhalten, stellen Sie bitte bei Ihrem eMail-Provider sicher, dass alle Filter oder Spamroutinen nicht f&uuml;r eMails von praktika.de gelten.</p>
<?php
}
bodyoff();
?>