<?
$sprachbasisdatei = "/home/praktikanten/mypassword.phtml";

require("/home/praktika/etc/config.inc.php"); 

if (!isset($_SESSION['s_loggedin']) || $_SESSION['s_loggedin'] == false) {
	header('Location: http://'.$_SERVER['HTTP_HOST'].'/login');
}

$_SESSION['restricted'] = RESTRICTED_COMPANY;
$_SESSION['current_user_group'] = USER_GROUP_COMPANIES;

pageheader(array('page_title' => '&Auml;nderung Ihres Passwortes'));

if (!isset($_POST['save']) ||
	!isset($_POST['passwort']) ||
	empty($_POST['passwort']) ||
	$_POST['passwort'] != $_POST['passwort2']) {
	
	if (isset($_POST['save'])) {
		echo '<p class="error">'.$language['strNichtGeaendert'].'</p>'."\n";
	}
	if (isset($_POST['save']) && $_POST['passwort'] != $_POST['passwort2']) {
		echo '<p class="error">'.$language['strEingabeWiederholung'].'</p>'."\n";
	}
	
	echo '<form action="/firmen/newpassword/" method="post" name="newpassword">'."\n";
	echo '	<h4>'.$language['strNeuesPW'].'</h4>'."\n";
	echo '	<fieldset>'."\n";
	echo '		<p>'."\n";
	echo '			<label for="pwd"'.((isset($_POST['save']) && isset($_POST['passwort']) && (empty($_POST['passwort']) || $_POST['passwort'] != $_POST['passwort2'])) ? ' class="error"' : '').'>'.$language['strZugangsPW'].'</label>'."\n";
	echo '			<input type="password" id="pwd" name="passwort" maxlength="35" value="" />'."\n";
	echo '		</p>'."\n";
	echo '		<p>'."\n";
	echo '			<label for="pwd2"'.((isset($_POST['save']) && isset($_POST['passwort2']) && (empty($_POST['passwort']) || $_POST['passwort'] != $_POST['passwort2'])) ? ' class="error"' : '').'>'.$language['strPWWiederholung'].'</label>'."\n";
	echo '			<input type="password" id="pwd2" name="passwort2" maxlength="35" value="" />'."\n";
	echo '		</p>'."\n";
	echo '	</fieldset>'."\n";
	echo '	<fieldset class="control_panel">'."\n";
	echo '		<p>'."\n";
	echo '			<button type="submit" name="save" value="speichern"><span><span><span>SPEICHERN</span></span></span></button>'."\n";
	echo '		</p>'."\n";
	echo '		<p>'."\n";
	echo '			<button type="button" name="back" value="zur&uuml;ck zur Bearbeiter&uuml;bersicht" onclick="location.href=\'/firmen/bearbeiter/\'"><span><span><span>ZUR&Uuml;CK</span></span></span></button>'."\n";
	echo '		</p>'."\n";
	echo '	</fieldset>'."\n";
	echo '</form>'."\n";
} elseif (	isset($_POST['save']) &&
			isset($_POST['passwort']) &
			!empty($_POST['passwort']) &
			$_POST['passwort'] == $_POST['passwort2']) {

	/* einfuegestring zusammensetzen */
	$insertstring = 'UPDATE bearbeiter SET passwort = OLD_PASSWORD(\''.mysql_real_escape_string($_POST['passwort']).'\'), passwort_plain = \''.mysql_real_escape_string($_POST['passwort']).'\', modify=NOW() WHERE id = '.intval($_SESSION['s_loginid']); 
	
	/* datensatz einfuegen */
	mysql_db_query($database_db,$insertstring,$praktdbmaster); 
	
	/* Logfile eintragen */
	$fp = fopen($logfile, 'a');
	fputs($fp, $insertstring);
	fputs($fp, "\n");
	fclose($fp);
	
	echo '<p class="success">Ihr Passwort wurde ge&auml;ndert !!</p>'."\n";
	echo '<p class="success">Die &Auml;nderung wird bei Ihrem n&auml;chsten Login wirksam werden!</p>'."\n";
	echo '<div class="control_panel">'."\n";
	echo '	<p>'."\n";
	echo '		<button type="button" name="back" value="zur&uuml;ck zur Bearbeiter&uuml;bersicht" onclick="location.href=\'/firmen/bearbeiter/\'"><span><span><span>ZUR&Uuml;CK</span></span></span></button>'."\n";
	echo '	</p>'."\n";
	echo '</div>'."\n";
}

bodyoff();
?>