<?
$sprachbasisdatei = "/home/praktikanten/commerce/zahlung_cc_bp.phtml";
$sprachbasisdatei2 = "/home/praktikanten/teilsuche_geld.phtml";

require("/home/praktika/etc/config.inc.php");

if (!isset($_SESSION['s_loggedin']) || $_SESSION['s_loggedin'] == false) {
	header('Location: http://'.$_SERVER['HTTP_HOST'].'/login');
	exit();
}

if ($_SESSION['produktID'] == 15 || $_SESSION['produktID'] == 16 || $_SESSION['produktID'] == 18 || $_SESSION['produktID'] == 54 || $_SESSION['produktID'] == 55 || $_SESSION['produktID'] == 56 || $_SESSION['produktID'] == 57) {
	$_SESSION['sidebar'] = 'stelle';
}

$_SESSION['sidebar'] = 'none';
$_SESSION['restricted'] = RESTRICTED_COMPANY;
$_SESSION['current_user_group'] = USER_GROUP_COMPANIES;
$_SESSION['current_page'] = PAGE_PUBLISH_JOBS;

$waehrung  = '&euro;';
$waehrung2 = 'EUR';
$hidepay = false;
$fortsetzen = false;

$strCustErrorMessage = $language['strKorrektausfuellen'];

if (isset($_POST['CardNumber'])) {
	$CardNumber = ereg_replace(' ', '', $_POST['CardNumber']);
}

pageheader(array('page_title' => 'Zahlung per Kreditkarte erfolgt'));

if (isset($_POST['submit_trans']) && ((isset($_POST['ExpMon']) && $_POST['ExpMon'] != '0') || (isset($_POST['ExpYear']) && $_POST['ExpYear'] != '0'))) {
	require("/home/praktika/etc/check_cc.inc.php");
	if (strlen($_POST['CardNumber']) > 1 and strlen($_POST['CardType']) > 1 ) {
		if ( isset($_POST['CardNumber']) ) {
			if (CCValidationSolution($_POST['CardNumber']) == true) {
				$strCustErrorMessage = 'The '.$_POST['CardType'].' number entered <em>is</em> valid';
				$fortsetzen = true;
			}
		} else {
			$Number = '';
		}
	} /* end if */

	if (($fortsetzen == true && isset($_POST['pay'])) || (isset($_POST['pay']) && isset($_POST['secondsubmit']))) {
		$hidepay = true;

		if (!isset($zahlkey)) {
			srand((double)microtime()*1000000);
			$zufallsid = md5(uniqid(rand()));
			$zahlkey = substr($zufallsid, -8); 
		}
		
		echo '<p>Vielen Dank für Ihre Kreditkartenzahlung</p>'."\n";
		
		foreach ($_SESSION['sql_query'] as $key => $value) {
			$res = mysql_db_query($database_comm,$value,$praktdbmaster);
		
			//nur fuer Tabelle "buchungen" INSERT kommasepariert zusammensetzen
			if ($key < 100) {
				$_SESSION['ProduktBuchungen'] .= $key == 0 ? mysql_insert_id() : ','.mysql_insert_id();
			}
			
			unset($_SESSION['sql_query'][$key]);
		}

		//wenn Komfort-Buchung und Basis schon vorhanden, dann wird Basis-Auslaufdatum auf Komfort-Anfangsdatum gesetzt
		if (($_SESSION['produktID'] == 15 || $_SESSION['produktID'] == 57) && $_SESSION['s_firmenlevel'] == 1) {
			$updateBasis = 'UPDATE buchungen SET zeitraum_bis = '.$_SESSION['zeitraum_von'].' WHERE stammid = '.$_SESSION['s_firmenid'].' AND (produktid = 18 OR produktid = 54 OR produktid = 55 OR produktid = 56);';
			$res = mysql_db_query($database_comm,$updateBasis,$praktdbmaster);
		}

		$final['stammid'] = intval($_SESSION['s_firmenid']);
		$final['bearbeiterid'] = intval($_SESSION['s_loginid']);
		$final['bestellid'] = $_SESSION['ProduktBuchungen'];
		$final['zahlungsart'] = 'kreditkarte';
		$final["kartentyp"] = mysql_real_escape_string($_POST['CardType']);
		$final["eigentuemer"] = mysql_real_escape_string($_POST['card_owner1']);
		$final["firma"] = mysql_real_escape_string($_POST['card_owner2']);
		$final["kartennummer"] = mysql_real_escape_string($_POST['CardNumber']);
		$final["kpruefnummer"] = mysql_real_escape_string($_POST['CardPruefNumber']);
		$final["monat"] = mysql_real_escape_string($_POST['ExpMon']);
		$final["jahr"] = mysql_real_escape_string($_POST['ExpYear']);
		$final['summe'] =  mysql_real_escape_string($_SESSION['gesamtPreisOhne']);
		$final['waehrung'] = "EUR";
		$final['ip'] = $ip;
		$final['host'] = $host;
		$final['datum_eintrag'] = date('Y-m-d');
		$final['eintrag_unix'] = time();
		$final['zahlkey'] = mysql_real_escape_string($zahlkey);
		
		$sqlQuery = 'INSERT INTO zahlungen SET ';
		
		foreach ($final as $key => $value) {
			$sqlQuery .= $key.' = \''.mysql_real_escape_string($value).'\', ';
		}

		$sqlQuery = substr($sqlQuery, 0, (strlen($sqlQuery) - 2));
		$res = mysql_db_query($database_comm, $sqlQuery, $praktdbmaster);
		
		$zahlungsid = mysql_insert_id();
	
		echo '<p class="success">Ihre Zahlungsdaten sind von unserem System erfolgreich gepr&uuml;ft worden!</p>'."\n";

		// infomail Kreditkarte
		$emailobj = new emailtemplate(72);
		$emailobj->replace('{eigentuemer}',$final['eigentuemer']);
		$emailobj->replace('{datum_eintrag}',$final['datum_eintrag']);
		$emailobj->replace('{firma}',$final['firma']);
		$emailobj->replace('{bruttosumme}',($final['summe']*(1+($mwst_satz/100))));
		$emailobj->replace('{gesamt}',$_SESSION['gesamtPreis']);
		$emailobj->send_email();
		unset($emailobj);
		
		if (isset($_POST['pay'])) {
			echo '<p class="success">Ihre Zahlung per Kreditkarte wurde im System erfasst und verarbeitet.</p>'."\n";

			echo '<p class="success">Ihre Buchung wurde ordnungsgem&auml;&szlig; empfangen. Sie k&ouml;nnen Ihre Rechnungen jederzeit im Recruiting Center im Men&uuml;punkt &quot;Firmendaten&quot; unter &quot;Mitgliedschaft und Rechnungen&quot; einsehen oder nochmalig ausdrucken.</p>'."\n";
			
			if ($_SESSION['produktID'] == 15 || $_SESSION['produktID'] == 16 || $_SESSION['produktID'] == 18 || $_SESSION['produktID'] == 54 || $_SESSION['produktID'] == 55 || $_SESSION['produktID'] == 56 || $_SESSION['produktID'] == 57) {
				$ProduktBuchungen = explode(',',$_SESSION['ProduktBuchungen']);
				unset($_SESSION['ProduktBuchungen']);
				
				foreach ($ProduktBuchungen as $key) {
					$sql_query = 'UPDATE buchungen SET zahlungid = '.$zahlungsid.', gezahlt = \'true\', modify = NOW() WHERE stammid = '.$_SESSION['s_firmenid'].' AND id = '.$key;
					$res = mysql_db_query($database_comm,$sql_query,$praktdbmaster);
					
					if (isset($_SESSION['zusatzLeistungen']) && array_key_exists(6,$_SESSION['zusatzLeistungen'])) {
						$sql_query = 'UPDATE firmen SET searchtop = \'true\', modify = NOW() WHERE id = '.$_SESSION['s_firmenid'];
						$res = mysql_db_query($database_db,$sql_query,$praktdbmaster);
					}
					
				}
			
				$sql_query = 'UPDATE firmen_prop_assign SET firmenlevel = '.$_SESSION['chosen_firmenlevel'].', modify = NOW() WHERE firmenid = '.$_SESSION['s_firmenid'];
				$res = mysql_db_query($database_db,$sql_query,$praktdbmaster);
			
				$_SESSION['s_firmenlevel'] = $_SESSION['chosen_firmenlevel'];

				$sql_query = 'UPDATE stellen SET datum_verfall = \''.$_SESSION['zeitraum_bis_verfall'].'\' WHERE inactive = \'false\' AND firmenid = '.$_SESSION['s_firmenid'];
				$res = mysql_db_query($database_db,$sql_query,$praktdbmaster);
				unset($_SESSION['zeitraum_bis_verfall']);
				
				//Buchungsbestaetigung senden
				$emailQuery = mysql_query('SELECT anrede, name, email FROM '.$database_db.'.bearbeiter WHERE id = '.intval($_SESSION['s_loginid']), $praktdbslave);
				$email = mysql_result($emailQuery, 0, 'email');
				
				$emailobj = new emailtemplate(102);
				$emailobj->replace('{anrede}', 'Sehr geehrte'.(mysql_result($emailQuery, 0, 'anrede') == 'Herr' ? 'r ' : ' ').mysql_result($emailQuery, 0, 'anrede').' '.mysql_result($emailQuery, 0, 'name'));
				
				$produkteMailHTML = '';
				$produkteMailPLAIN = '';
				$nettoPreis = 0;
				$bruttoPreis = 0;
				$mwstPreis = 0;
				
				foreach ($_SESSION['produkt'] as $key => $value) {
					$produkteMailHTML .= '				<tr>'."\n";
					$produkteMailHTML .= '					<td><strong>'.$value['bezeichnung'].'</strong><br />'.$value['beschreibung'].'</td>'."\n";
					$produkteMailHTML .= '					<td><strong>'.$value['preis'].',00 &euro;</strong></td>'."\n";
					$produkteMailHTML .= '					<td><strong>'.$value['buchmenge'].'</strong></td>'."\n";
					$produkteMailHTML .= '					<td><strong>'.intval($value['buchmenge']) * intval($value['preis']).',00 &euro;</strong></td>'."\n";
					$produkteMailHTML .= '				</tr>'."\n";
					
					$produkteMailPLAIN .= 'Produkt: '.$value['bezeichung']."\n";
					$produkteMailPLAIN .= 'Einzelpreis: '.$value['preis']."\n";
					$produkteMailPLAIN .= 'Menge: '.$value['buchmenge']."\n";
					$produkteMailPLAIN .= 'Preis: '.intval($value['buchmenge']) * intval($value['preis'])."\n\n";
					
					$nettoPreis += intval($value['buchmenge']) * intval($value['preis']);
					$bruttoPreis += intval($value['buchmenge']) * intval($value['preis']) * 1.19;
				}
				
				$mwstPreis = $bruttoPreis - $nettoPreis;
				
				$emailobj->replace('{produkteHTML}', $produkteMailHTML);
				$emailobj->replace('{produktePLAIN}', $produkteMailPLAIN);
				$emailobj->replace('{nettopreis}', number_format($nettoPreis, 2, ',', '.'));
				$emailobj->replace('{bruttopreis}', number_format($bruttoPreis, 2, ',', '.'));
				$emailobj->replace('{mwstpreis}', number_format($mwstPreis, 2, ',', '.'));
				$emailobj->send_email($email);
				unset($emailobj);
				unset($_SESSION['produkt']);

				//agge: lieber loesung mit header funktion, damit doppelte eintraege in der tabelle zahlungen durch reload der page vermieden werden
				if (isset($_SESSION['jobAd']['stellenid'])) {
					if (isset($_SESSION['buchungsseite']) && $_SESSION['buchungsseite'] == 'activate') {
						unset($_SESSION['nextJobAdLocked']);
						header('Location: /firmen/stelle/'.$_SESSION['jobAd']['stellenid'].'/activate.html');
						exit();
					} elseif (isset($_SESSION['buchungsseite']) && $_SESSION['buchungsseite'] == 'layout') {
						unset($_SESSION['nextJobAdLocked']);
						header('Location: /firmen/stelle/'.$_SESSION['jobAd']['stellenid'].'/layout.html');
						exit();
					} else {
						header('Location: /firmen/angeboteliste/');
						exit();
					}
				} else {
					header('Location: /firmen/angeboteliste/');
					exit();
				}
			} else {
				$produktquery = 'SELECT pbuchpath, bezeichnung, prop_db_field FROM produkte WHERE id = '.$_SESSION['produktID'];
				$produktresults = mysql_db_query($database_comm,$produktquery,$praktdbslave);
				$produkt = mysql_fetch_array($produktresults);
				
				$sql_query = 'UPDATE firmen_prop_assign SET '.$produkt['prop_db_field'].' = \'true\', modify = NOW() WHERE firmenid = '.$_SESSION['s_firmenid'];
				$res = mysql_db_query($database_db,$sql_query,$praktdbmaster);
			
				header('Location: '.$produkt['pbuchpath'].'?pid='.$_SESSION['produktID']); //agge: lieber loesung mit header funktion, damit doppelte eintraege in der tabelle zahlungen durch reload der page vermieden werden
				exit();
			}
		}
	}
}

if ($hidepay == false) {
	if (isset($_POST['submit_trans'])) {
		echo '<p class="error">'.$language['strEingabefehler'].'</p>'."\n";
	}

	echo '<h3>Zur Zahlung ausgew&auml;hlte Buchungen</h3>'."\n";

	echo '<table>'."\n";
	echo '	<colgroup>'."\n";
	echo '		<col width="50%" />'."\n";
	echo '		<col width="25%" />'."\n";
	echo '		<col width="25%" />'."\n";
	echo '	</colgroup>'."\n";
	echo '	<tr>'."\n";
	echo '		<th>gebuchte Produkte</th>'."\n";
	echo '		<th>Rechnungsdatum</th>'."\n";
	echo '		<th>Preis</th>'."\n";
	echo '	</tr>'."\n";

	$package = mysql_db_query($database_comm,'SELECT * FROM produkte WHERE id = '.$_SESSION['produktID'],$praktdbslave);

	echo '	<tr>'."\n";
	echo '		<td>'.mysql_result($package,0,'bezeichnung').'</td>'."\n";
	echo '		<td>am '.date('d.m.Y').'</td>'."\n"; 
	echo '		<td>EUR '.sprintf('%01.2f',mysql_result($package,0,'preis')).'</td>'."\n";
	echo '	</tr>'."\n";

	if (isset($_SESSION['zusatzLeistungen']) && is_array($_SESSION['zusatzLeistungen'])) {
		echo '	<tr>'."\n";
		echo '		<td colspan="3"><b>Zusatzleistungen:</b></td>'."\n";
		echo '	</tr>'."\n";
		
		foreach ($_SESSION['zusatzLeistungen'] as $key) {
			$liste = mysql_db_query($database_comm,'SELECT * FROM produkte WHERE id = '.$key,$praktdbslave);
			
			echo '	<tr>'."\n";
			echo '		<td>'.mysql_result($liste,0,'bezeichnung').'</td>'."\n";
			echo '		<td>am '.date('d.m.Y').'</td>'."\n"; 
			echo '		<td>EUR '.sprintf('%01.2f',mysql_result($liste,0,'preis')).'</td>'."\n";
			echo '	</tr>'."\n";
		}
	}

	$mwst = ($_SESSION['produktPreis'] * (1 + ($mwst_satz / 100))) -  $_SESSION['produktPreis'];

	echo '	<tr>'."\n";
	echo '		<td>&nbsp;</td>'."\n";
	echo '		<td>Gessamt netto:</td>'."\n";
	echo '		<td>EUR '.sprintf('%01.2f', $_SESSION['produktPreis']).'</td>'."\n";
	echo '	</tr>'."\n";
	echo '	<tr>'."\n";
	echo '		<td>&nbsp;</td>'."\n";
	echo '		<td>MwSt. '.$mwst_satz.'%:</td>'."\n";
	echo '		<td>EUR '.sprintf('%01.2f',$mwst).'</td>'."\n";
	echo '	</tr>'."\n";
	echo '	<tr>'."\n";
	echo '		<td>&nbsp;</td>'."\n";
	echo '		<td><b><u>Gesamt</u></b></td>'."\n";
	echo '		<td><b><u>EUR '.sprintf('%01.2f', $_SESSION['gesamtPreis']).'</u></b></td>'."\n";
	echo '	</tr>'."\n";
	echo '</table>'."\n";
	echo '<h4 style="margin-top: 1em;">Bitte geben Sie nun Ihre Kreditkartendaten ein:</h4>'."\n";
	echo '<form method="post" action="http://'.$_SERVER['HTTP_HOST'].$_SERVER['PHP_SELF'].'" name="formular">'."\n";
	
	if (isset($_POST['submit_trans'])) {
		echo '	<input type="hidden" name="secondsubmit" value="1" />'."\n";
	}
	
	if (!isset($_POST['zahlkey'])) {
		srand((double) microtime() * 1000000);
		$zufallsid = md5(uniqid(rand()));
		$_POST['zahlkey'] = substr ($zufallsid, -8);
	}

	echo '	<input type="hidden" name="zahlkey" value="'.$_POST['zahlkey'].'" />'."\n";
	echo '	<input type="hidden" name="gesamt" value="'.$_SESSION['gesamtPreis'].'" />'."\n";
	echo '	<fieldset>'."\n";
	echo '		<p class="hint" style="text-align: left; width: 100%;">Meldung: <span class="error"><b>'.$strCustErrorMessage.'</b></span></p>'."\n";
	echo '		<p>'."\n";
	echo '			<label for="CardType"'.((isset($_POST['submit_trans']) && isset($_POST['CardType']) && $_POST['CardType'] == '0') ? ' class="error"' : '').'>'.$language['strTypeCC'].'</label>'."\n";
	echo '			<select id="CardType" name="CardType" size="1">'."\n";
	echo '				<option value="0">'.$language['strWaehlen'].'</option>'."\n";
	echo '				<option value="VisaCard"'.((isset($_POST['CardType']) && $_POST['CardType'] == 'VisaCard') ? ' selected="selected"' : '').'>VISA</option>'."\n";
	echo '				<option value="MasterCard"'.((isset($_POST['CardType']) && $_POST['CardType'] == 'MasterCard') ? ' selected="selected"' : '').'>Master / Euro Card</option>'."\n";
	echo '				<option value="AmExCard"'.((isset($_POST['CardType']) && $_POST['CardType'] == 'AmExCard') ? ' selected="selected"' : '').'>American Express</option>'."\n";
	echo '			</select>'."\n";
	echo '		</p>'."\n";
	echo '		<p>'."\n";
	echo '			<label for="card_owner1"'.((isset($_POST['submit_trans']) && isset($_POST['card_owner1']) && empty($_POST['card_owner1'])) ? ' class="error"' : '').'>'.$language['strKarteneigentuemer'].'</label>'."\n";
	echo '			<input type="text" id="card_owner1" name="card_owner1" size="25" maxlength="35" value="'.(isset($_POST['card_owner1']) ? $_POST['card_owner1'] : $_SESSION['s_vname']." ".$_SESSION['s_name']).'" />'."\n";
	echo '		</p>'."\n";

	if (isset($_POST['card_owner2'])) {
		$karteninhaber = $_POST['card_owner2'];
	} else {
        $firmenname = mysql_db_query($database_db,'SELECT firma FROM firmen WHERE id = '.$_SESSION['s_firmenid'],$praktdbslave);
       	$karteninhaber = mysql_result($firmenname,0,'firma');
	}

	echo '		<p>'."\n";
	echo '			<label for="card_owner2"'.((isset($_POST['submit_trans']) && isset($_POST['card_owner2']) && empty($_POST['card_owner2'])) ? ' class="error"' : '').'>'.$language['strFirma'].'</label>'."\n";
	echo '			<input type="text" id="card_owner2" name="card_owner2" size="25" maxlength="35" value="'.$karteninhaber.'" />'."\n";
	echo '		</p>'."\n";
	echo '		<p>'."\n";
	echo '			<label for="CardNumber"'.((isset($_POST['submit_trans']) && isset($_POST['CardNumber']) && empty($_POST['CardNumber'])) ? ' class="error"' : '').'>'.$language['strKartennummer'].'</label>'."\n";
	echo '			<input type="text" id="CardNumber" name="CardNumber" size="25" maxlength="35" value="'.(isset($_POST['CardNumber']) ? $_POST['CardNumber'] : '').'" />'."\n";
	echo '		</p>'."\n";
	echo '		<p>'."\n";
	echo '			<label for="CardPruefNumber"'.((isset($_POST['submit_trans']) && isset($_POST['CardPruefNumber']) && empty($_POST['CardPruefNumber'])) ? ' class="error"' : '').'>'.$language['strKartenpruefnummer'].'</label>'."\n";
	echo '			<input type="text" id="CardPruefNumber" name="CardPruefNumber" size="4" maxlength="4" value="'.(isset($_POST['CardPruefNumber']) ? $_POST['CardPruefNumber'] : '').'" />'."\n";
	echo '		</p>'."\n";
	echo '		<p>'."\n";
	echo '			<label for="ExpMon"'.(((isset($_POST['submit_trans']) && isset($_POST['ExpMon']) && $_POST['ExpMon'] == 0) || (isset($_POST['submit_trans']) && isset($_POST['ExpYear']) && $_POST['ExpYear'] == 0)) ? ' class="error"' : '').'>'.$language['strGueltig'].' (Monat / Jahr)</label>'."\n";
	echo '			<select id="ExpMon" name="ExpMon" class="month">'."\n";
	echo '				<option value="0">--</option>'."\n";
	
	for ($i = 1; $i <= 12; $i++) {
		echo '				<option value="'.$i.'"';
		if (isset($_POST['ExpMon']) && $i == $_POST['ExpMon']) {
			echo ' selected="selected"';
		}
		echo '>'.$i.'</option>'."\n";
	}
	
	echo '			</select> / '."\n";
	echo '			<select id="ExpYear" name="ExpYear" class="year">'."\n";
	echo '				<option value="0">--</option>'."\n";
	
	for ($i = date("Y"); $i <= date("Y") + 15; $i++) {
		echo '			<option value="'.$i.'"';
		if (isset($_POST['ExpYear']) && $i == $_POST['ExpYear']) {
			echo ' selected="selected"';
		}
		echo '>'.$i.'</option>'."\n";
	}
	
	echo '			</select>'."\n";
	echo '		</p>'."\n";
	echo '		<p class="hint" style="text-align: left; width: 100%;">praktika.de best&auml;tigt hiermit ausdr&uuml;cklich, dass pers&ouml;nliche Daten, die in Verbindung mit dem Bestellvorgang eingegeben werden, vertraulich behandelt und keinesfalls an Dritte weitergegeben werden.<br />Hinweis zur Zahlung per Kreditkarte: Wenn Sie Ihre Kreditkartendaten eintragen, werden die Daten &uuml;ber eine Datenleitung online &uuml;bertragen. Dieser Service bleibt bis zur vollst&auml;ndigen Bezahlung Eigentum von praktika.de</p>'."\n";

	if (isset($_POST['submit_trans']) && !isset($_POST['pay'])) {
		echo '	<p class="error"><b>Bitte best&auml;tigen Sie die nachfolgende Checkbox, wenn Sie mit dem Kreditkartenaufrag einverstanden sind!</b></p>'."\n";
	}
	
	echo '		<p class="checkboxes clearfix">'."\n";
	echo '			<input type="checkbox" id="pay" name="pay" value="1" '.(isset($_POST['pay']) ? ' checked="checked"' : '').' />'."\n";
	echo '			<label for="pay">Hiermit erm&auml;chtige ich den Betreiber von www.praktika.de, PRAKTIKA GmbH, den oben genannten Betrag von meiner oben genannten Kreditkarte einzuziehen. Diese Belastung kann ab sofort erfolgen. Ein Widerruf bzw. R&uuml;ckgabe des Produktes ist nicht m&ouml;glich, da dieser Service naturgem&auml;ß für die R&uuml;ckgabe ungeeignet ist.</label>'."\n";
	echo '		</p>'."\n";
	echo '		<p class="hint" style="text-align: left; width: 100%;">'.$language['strErmachtigungCC2'].'</p>'."\n";
	echo '		<p>'.$language['strTransakbeschreib'].'<br /><br />'.$language['strTransakhinweis'].'</p>'."\n";

	echo '	</fieldset>'."\n";
	echo '	<fieldset class="control_panel">'."\n";
	echo '		<p>'."\n";
	echo '			<button type="submit" name="submit_trans" value="'.(isset($_POST['submit_trans']) ? 'TRANSAKTION WIEDERHOLEN' : 'TRANSAKTION STARTEN').'"><span><span><span>'.(isset($_POST['submit_trans']) ? 'TRANSAKTION WIEDERHOLEN' : 'TRANSAKTION STARTEN').'</span></span></span></button>'."\n";
	echo '		</p>'."\n";
	echo '		<p>'."\n";
	echo '			<button type="button" name="back" value="zur&uuml;ck" onclick="location.href=\'/firmen/stelle/buchung/\'"><span><span><span>ZUR&Uuml;CK</span></span></span></button>'."\n";
	echo '		</p>'."\n";
	echo '	</fieldset>'."\n";
	echo '</form>'."\n";

	echo '<p class="hint" style="text-align: left;">Sie benutzen die folgende IP-Adresse: ('.$ip.') Diese Benutzerdaten werden bis zur endg&uuml;ltigen Bezahlung protokolliert. Mit dieser IP-Adresse kann jeder Internetnutzer &uuml;ber seinen Provider bzw. Telefongesellschaft zweifelsfrei ermittelt werden. praktika.de beh&auml;lt sich vor, bei zur&uuml;ckgewiesener Zahlung diese Information im Rahmen einer gerichtlichen Geltendmachung zu verwenden. Jeder Missbrauch wird strafrechtlich verfolgt und polizeilich angezeigt.<br /><br />F&uuml;r Fragen oder Erl&auml;uterungen zu diesem Service senden Sie bitte Ihre eMail an: <a href="mailto:Kreditkarte@praktika.de">Kreditkarte@praktika.de</a></p>'."\n";
}

$_SESSION['sidebar'] = '';
bodyoff();
?>