<?
$sprachbasisdatei = "/home/praktikanten/teilsuche_geld.phtml";

require("/home/praktika/etc/config.inc.php");

if (!isset($_SESSION['s_loggedin']) || $_SESSION['s_loggedin'] == false) {
	header('Location: http://'.$_SERVER['HTTP_HOST'].'/login');
	exit();
}

if ($_SESSION['produktID'] == 15 || $_SESSION['produktID'] == 16 || $_SESSION['produktID'] == 18 || $_SESSION['produktID'] == 54 || $_SESSION['produktID'] == 55 || $_SESSION['produktID'] == 56 || $_SESSION['produktID'] == 57) {
	$_SESSION['sidebar'] = 'stelle';
}

$_SESSION['sidebar'] = 'none';
$_SESSION['restricted'] = RESTRICTED_COMPANY;
$_SESSION['current_user_group'] = USER_GROUP_COMPANIES;
$_SESSION['current_page'] = PAGE_PUBLISH_JOBS;

$waehrung  = '&euro;';
$waehrung2 = 'EUR';

pageheader(array('page_title' => 'Zahlung per Rechnung gew&auml;hlt'));

echo '<p>'.$language["strDanke"].'</p>'."\n";

if (!isset($zahlkey)) {
	srand((double)microtime()*1000000);
	$zufallsid = md5(uniqid(rand()));
	$zahlkey = substr($zufallsid, -8); 
}

foreach ($_SESSION['sql_query'] as $key => $value) {
	$res = mysql_db_query($database_comm,$value,$praktdbmaster);

	//nur fuer Tabelle "buchungen" INSERT kommasepariert zusammensetzen
	if ($key < 100) {
		$_SESSION['ProduktBuchungen'] .= $key == 0 ? mysql_insert_id() : ','.mysql_insert_id();
	}
	
	unset($_SESSION['sql_query'][$key]);
}
	
//wenn Komfort-Buchung und Basis schon vorhanden, dann wird Basis-Auslaufdatum auf Komfort-Anfangsdatum gesetzt
if (($_SESSION['produktID'] == 15 || $_SESSION['produktID'] == 57) && $_SESSION['s_firmenlevel'] == 1) {
	$updateBasis = 'UPDATE buchungen SET zeitraum_bis = '.$_SESSION['zeitraum_von'].' WHERE stammid = '.$_SESSION['s_firmenid'].' AND (produktid = 18 OR produktid = 54 OR produktid = 55 OR produktid = 56);';
	$res = mysql_db_query($database_comm,$updateBasis,$praktdbmaster);
}

$final['stammid'] = intval($_SESSION['s_firmenid']);
$final['bearbeiterid'] = intval($_SESSION['s_loginid']);
$final['bestellid'] = $_SESSION['ProduktBuchungen'];
$final['zahlungsart'] = 'rechnung';
$final['summe'] =  mysql_real_escape_string($_SESSION['gesamtPreisOhne']);
$final['waehrung'] = "EUR";
$final['ip'] = $ip;
$final['host'] = $host;
$final['datum_eintrag'] = date('Y-m-d');
$final['eintrag_unix'] = time();
$final['zahlkey'] = mysql_real_escape_string($zahlkey);

//INSERT
$sqlQuery = 'INSERT INTO zahlungen SET ';

foreach ($final as $key => $value) {
	$sqlQuery .= $key.' = \''.mysql_real_escape_string($value).'\', ';
}

$sqlQuery = substr($sqlQuery, 0, (strlen($sqlQuery) - 2));
$res = mysql_db_query($database_comm, $sqlQuery, $praktdbmaster);

$zahlungsid = mysql_insert_id();

// infomail Rechnung
$emailobj = new emailtemplate(73);
$emailobj->replace("{gesamt}",$_SESSION['gesamtPreis']);
$emailobj->replace("{vname}",$_SESSION['s_vname']);
$emailobj->replace("{name}",$_SESSION['s_name']);
$emailobj->replace("{datum_eintrag}",$final["datum_eintrag"]);
$emailobj->send_email();
unset($emailobj);

echo '<p class="success">Ihre Buchung wurde ordnungsgem&auml;&szlig; empfangen. Sie k&ouml;nnen Ihre Rechnungen jederzeit im Recruiting Center im Men&uuml;punkt &quot;Firmendaten&quot; unter &quot;Mitgliedschaft und Rechnungen&quot; einsehen oder nochmalig ausdrucken.</p>'."\n";

if ($_SESSION['produktID'] == 15 || $_SESSION['produktID'] == 16 || $_SESSION['produktID'] == 18 || $_SESSION['produktID'] == 54 || $_SESSION['produktID'] == 55 || $_SESSION['produktID'] == 56 || $_SESSION['produktID'] == 57) {
	$ProduktBuchungen = explode(',',$_SESSION['ProduktBuchungen']);
	unset($_SESSION['ProduktBuchungen']);
	
	foreach ($ProduktBuchungen as $key) {
		$sql_query = 'UPDATE buchungen SET zahlungid = '.$zahlungsid.', gezahlt = \'true\', modify = NOW() WHERE stammid = '.$_SESSION['s_firmenid'].' AND id = '.$key;
		$res = mysql_db_query($database_comm,$sql_query,$praktdbmaster);
		echo $sql_query;
		if (isset($_SESSION['zusatzLeistungen']) && array_key_exists(6,$_SESSION['zusatzLeistungen'])) {
			$sql_query = 'UPDATE firmen SET searchtop = \'true\', modify = NOW() WHERE id = '.$_SESSION['s_firmenid'];
			$res = mysql_db_query($database_db,$sql_query,$praktdbmaster);
		}
		
	}

	$sql_query = 'UPDATE firmen_prop_assign SET firmenlevel = '.$_SESSION['chosen_firmenlevel'].', modify = NOW() WHERE firmenid = '.$_SESSION['s_firmenid'];
	$res = mysql_db_query($database_db,$sql_query,$praktdbmaster);

	$sql_query = 'UPDATE stellen SET datum_verfall = \''.$_SESSION['zeitraum_bis_verfall'].'\' WHERE inactive = \'false\' AND firmenid = '.$_SESSION['s_firmenid'];
	$res = mysql_db_query($database_db,$sql_query,$praktdbmaster);
	unset($_SESSION['zeitraum_bis_verfall']);

	$_SESSION['s_firmenlevel'] = $_SESSION['chosen_firmenlevel'];

	//Buchungsbestaetigung senden
	$emailQuery = mysql_query('SELECT anrede, name, email FROM '.$database_db.'.bearbeiter WHERE id = '.intval($_SESSION['s_loginid']), $praktdbslave);
	$email = mysql_result($emailQuery, 0, 'email');
	
	$emailobj = new emailtemplate(102);
	$emailobj->replace('{anrede}', 'Sehr geehrte'.(mysql_result($emailQuery, 0, 'anrede') == 'Herr' ? 'r ' : ' ').mysql_result($emailQuery, 0, 'anrede').' '.mysql_result($emailQuery, 0, 'name'));
	
	$produkteMailHTML = '';
	$produkteMailPLAIN = '';
	$nettoPreis = 0;
	$bruttoPreis = 0;
	$mwstPreis = 0;
	
	foreach ($_SESSION['produkt'] as $key => $value) {
		$produkteMailHTML .= '				<tr>'."\n";
		$produkteMailHTML .= '					<td><strong>'.$value['bezeichnung'].'</strong><br />'.$value['beschreibung'].'</td>'."\n";
		$produkteMailHTML .= '					<td><strong>'.$value['preis'].',00 &euro;</strong></td>'."\n";
		$produkteMailHTML .= '					<td><strong>'.$value['buchmenge'].'</strong></td>'."\n";
		$produkteMailHTML .= '					<td><strong>'.intval($value['buchmenge']) * intval($value['preis']).',00 &euro;</strong></td>'."\n";
		$produkteMailHTML .= '				</tr>'."\n";
		
		$produkteMailPLAIN .= 'Produkt: '.$value['bezeichung']."\n";
		$produkteMailPLAIN .= 'Einzelpreis: '.$value['preis']."\n";
		$produkteMailPLAIN .= 'Menge: '.$value['buchmenge']."\n";
		$produkteMailPLAIN .= 'Preis: '.intval($value['buchmenge']) * intval($value['preis'])."\n\n";
		
		$nettoPreis += intval($value['buchmenge']) * intval($value['preis']);
		$bruttoPreis += intval($value['buchmenge']) * intval($value['preis']) * 1.19;
	}
	
	$mwstPreis = $bruttoPreis - $nettoPreis;
	
	$emailobj->replace('{produkteHTML}', $produkteMailHTML);
	$emailobj->replace('{produktePLAIN}', $produkteMailPLAIN);
	$emailobj->replace('{nettopreis}', number_format($nettoPreis, 2, ',', '.'));
	$emailobj->replace('{bruttopreis}', number_format($bruttoPreis, 2, ',', '.'));
	$emailobj->replace('{mwstpreis}', number_format($mwstPreis, 2, ',', '.'));
	$emailobj->send_email($email);
	unset($emailobj);
	unset($_SESSION['produkt']);
		
	//agge: lieber loesung mit header funktion, damit doppelte eintraege in der tabelle zahlungen durch reload der page vermieden werden
	if (isset($_SESSION['jobAd']['stellenid'])) {
		if (isset($_SESSION['buchungsseite']) && $_SESSION['buchungsseite'] == 'activate') {
			unset($_SESSION['nextJobAdLocked']);
			header('Location: /firmen/stelle/'.$_SESSION['jobAd']['stellenid'].'/activate.html');
			exit();
		} elseif (isset($_SESSION['buchungsseite']) && $_SESSION['buchungsseite'] == 'layout') {
			unset($_SESSION['nextJobAdLocked']);
			header('Location: /firmen/stelle/'.$_SESSION['jobAd']['stellenid'].'/layout.html');
			exit();
		} else {
			header('Location: /firmen/angeboteliste/');
			exit();
		}
	} else {
		header('Location: /firmen/angeboteliste/');
		exit();
	}
} else {
	$produktquery = 'SELECT pbuchpath, bezeichnung, prop_db_field FROM produkte WHERE id = '.$_SESSION['produktID'];
	$produktresults = mysql_db_query($database_comm,$produktquery,$praktdbslave);
	$produkt = mysql_fetch_array($produktresults);
	
	$sql_query = 'UPDATE firmen_prop_assign SET '.$produkt['prop_db_field'].' = \'true\', modify = NOW() WHERE firmenid = '.$_SESSION['s_firmenid'];
	$res = mysql_db_query($database_db,$sql_query,$praktdbmaster);

	header('Location: '.$produkt['pbuchpath'].'?pid='.$_SESSION['produktID']); //agge: lieber loesung mit header funktion, damit doppelte eintraege in der tabelle zahlungen durch reload der page vermieden werden
	exit();
}

$_SESSION['sidebar'] = '';
bodyoff(); ?>