<?php
include_once('/home/praktika/etc/config.inc.php');

# pageheader();

$_SESSION['restricted'] = RESTRICTED_CANDIDATE;
$_SESSION['current_page'] = PAGE_CAREER_CENTER;
$_SESSION['current_user_group'] = USER_GROUP_CANDIDATES;
$_SESSION['sidebar'] = '';

$availDirectories = array('messaging','daten','gesuche','passbild');

$pageHeaderArray = array(
	'page_title' => 'Karriere Center <span id="kCenterTitle"></span>',
	'grid_system' => '6-0',
	'scripts' => array('ajax/bcenter.js')
);

if (!empty($_POST['mode'])) {
	$parts = explode('/', $_POST['mode'], 2);

	if (in_array($parts[0], $availDirectories) === false) {
		$parts[0] = 'messaging';
		$parts[1] = 'index';
	}
	if(count($parts) < 2) $parts[1] = 'index';
} else {
		$parts[0] = 'messaging';
		$parts[1] = 'index';
}

if (!empty($_POST['mode'])) {
	eval('include \'/home/praktika/public_html/home/praktikanten/kcenter/'.$parts[0].'/'.urlencode($parts[1]).'.phtml\';');
}