<?
require("/home/praktika/etc/gb_config.inc.php"); 
praktikaInclude(array("db.php"));
$hDB = new Praktika_db();

if($_POST["act"] == "new") {
	mysql_query('INSERT INTO prakt2.firmenordner (firmenid,name,bereich,reihenfolge) 
		VALUES 
		('.intval($_SESSION['s_firmenid']).',
		"'.mysql_real_escape_string($_POST['titel']).'",
		'.intval($_POST['bereich']).', 100)', $praktdbmaster);
	
}

$editMode = true; 
include "/home/praktika/etc/navibaumfirmen.inc.php";