<?
 $sprachbasisdatei = "/home/praktikanten/mitglied.phtml";

if ($loginwer == "Bewerber") {
$unternehmen="no";
} elseif ($loginwer == "Unternehmen") {
$unternehmen="yes";
}

require("/home/praktika/etc/config.inc.php");

if($s_nutzerid>0) {
	header("Location: /home/praktikanten/kcenter/");
}
if($s_firmenid>0) {
	header("Location: /home/firmen/bcenter/");
}

if (isset($_REQUEST["sendemailverify"])) {

	// neues Emailsystem nutzen
	$aktstunde = date("H");
	if ($aktstunde <10) {
		$begruessung = "Guten Morgen";
	} elseif ($aktstunde > 19) {
		$begruessung = "Guten Abend";
	} else {
		$begruessung = "Hallo";
	}

	$verifykeyresults = mysql($database_db,"SELECT id, anrede, name, vname, email, id_md5 AS verifykey FROM nutzer WHERE email = '".$_REQUEST["email"]."'",$praktdbslave);


	// Templatesystem vorbereiten

	// datensaetze gefunden ? //
	$verifykeynum_rows = mysql_num_rows( $verifykeyresults );
	
	if ($verifykeynum_rows > 0) {
		$verifykeydaten = mysql_fetch_array( $verifykeyresults );

		$begruessung .= " ".$verifykeydaten["anrede"]." ".$verifykeydaten["name"];
		
		$emailobj = new emailtemplate(5);
		// Ersetzungen durchführen
		$mailto      = $verifykeydaten["email"];
		$emailobj->replace("{ansprache}",$begruessung);
		$emailobj->replace("{email}",$verifykeydaten["email"]);
		$emailobj->replace("{id}",$verifykeydaten["id"]);
		$emailobj->replace("{verifykey}",$verifykeydaten["verifykey"]);
		$emailobj->replace("{passwort}","wird nicht mitgesendet");
		
		// Bestaetigunsmail verschicken
		$emailobj->send_email($mailto);
		// Emailobjekt löschen
		unset($emailobj);
	
		$verifyemailsend = true;
	} else {
		$noaccouthere = "yes";
		$emailverifyfalse="yes";
	}
}

if ($loginwer == "Bewerber") {
	$passwdpfad="/home/praktikanten/passwdwindow.phtml";
	$s_unternehmen="no";

	if ($loginidemail != "" && $passwort != "") {

		$logincheck=sessionnutzerlogin($database_db,$loginidemail,$passwort,session_id());

		/* passwort richtig */
		if ($logincheck == "true") {
			require("/home/praktika/etc/login_bewerber.inc.php");

			if ($idremind == "yes") {
				setcookie ("c_lid", $s_loginid, time() + 31449600, "/");
			}
			$nutzergroup="nutzer";
			setcookie ("c_group", $nutzergroup, time() + 31449600, "/");

			if ($s_samesite=="yes") {
				if($s_uri) {
					header("Location: " . $s_uri);
					unset($s_uri);
				} else {
					header("Location: " . $uri);
				}
			} else {
				header("Location: /home/praktikanten/kcenter/");
				exit;
			}
		}


		// bei Fehlern
		if ($logincheck == "false"){
			$keinlogin="yes";
		}
		if ($logincheck == "passwdfalsch"){
			$passwdfalsch="yes";
		}
		if ($logincheck == "gesperrt"){
			$gesperrt="yes";
		}
		if ($logincheck == "emailverifyfalse"){
			$emailverifyfalse="yes";
		}
	}
	if ($passwort == "") $passwortleer="yes";
	if ($loginidemail == "") $loginleer="yes";
	//$fehler="yes";



} elseif ($loginwer == "Unternehmen") {
// ab hier folgt der Unternehmenszweig
	$passwdpfad="/home/firmen/passwdwindow.phtml";
	$unternehmen="yes";
	if ($loginidemail != "" && $passwort != "") {

		$logincheck=(sessionlogin($database_db,$loginidemail,$passwort,session_id()));
		if ($logincheck == "true"){
			require("/home/praktika/etc/login_firmen.inc.php");
			require("/home/praktika/etc/loginseiten.inc.php");

			$nutzergroup="unternehmen";
			setcookie ("c_group", $nutzergroup, time() + 31449600, "/");

			if ($idremind == "yes") {
				setcookie ("c_lid", $s_loginid, time() + 31449600, "/");
			}
			//echo substr_count($uri,"104.0.html");
			if (substr_count($uri,"?") >0 && substr_count($uri,"104.0.html") <1 && substr_count($uri,"/bewerber/index.phtml") <1 && substr_count($uri,"/home/quicklogin") <1 && substr_count($uri,"logout") <1) {
				//header("Location: " . $uri);
				// An Loginseite weiterleiten
				if (($s_firmenlevel < 1)  && (get_number_of_active_loginpages() > 0)) {
					loginpage($uri);
				} else {
					header("Location: " . $uri);
				}

			} else {
				//header("Location: /home/firmen/bcenter/");
				// An Loginseite weiterleiten
				if (($s_firmenlevel < 1)  && (get_number_of_active_loginpages() > 0)) {
					loginpage("/home/firmen/bcenter/");
				} else {
					header("Location: /home/firmen/bcenter/");
				}
			}
		}

		// bei Fehlern
		if ($logincheck == "false") {
			$keinlogin="yes";
		}
		if ($logincheck == "passwdfalsch") {
			$passwdfalsch="yes";
		}
		if ($logincheck == "gesperrt") {
			$gesperrt="yes";
		}
	}
	if ($passwort == "") $passwortleer="yes";
	if ($loginidemail == "") $loginleer="yes";
	//$fehler="yes";
}

pageheader(session_id(), session_name());


?>
      <table width="90%">
        <tr>
          <td><h1 class="layout1">Anmeldung für <? echo $language["str".$loginwer]; ?></h1>
            <? if ($verifyemailsend) {
				echo "<font color=\"red\" class=\"toppraktika\">Wir haben Ihnen die gewünschte Bestätigungsemail an Ihre Adresse zugesandt, bitte wechseln Sie nun in Ihr Postfach, um Ihren Accout zu bestätigen. Sollten Sie keine Email von uns erhalten haben, so bitten wir Sie auch in eventuellen Spam- oder Unerwünscht-Ordnern danach zu schauen. Vielen Dank.</font>"; 
            } elseif ($emailverifyfalse=="yes") {
            	if ($noaccouthere == "yes") {
            		echo "<font color=\"red\" class=\"toppraktika\">Die eingegebene Email - Adresse war nicht korrekt, bitte geben Sie nachfolgend Ihre korrekte Account-Adresse ein.</font>"; 
            	} else {
            		echo "<font color=\"red\" class=\"toppraktika\">Sie haben Ihren praktika.de Account noch nicht bestätigt, bitte klicken Sie auf den Link in der Email, die wir Ihnen nach der Accountregistrierung zukommen lassen haben.</font>"; 
            	}
            	?><br><br>
            	Um sich erneut die Bestätigungsemail zusenden zu lassen, geben Sie bitte nachfolgend Ihre Email-Adresse ein.
            	<form action="./" method="post">
              	<table border="0" width="400">
                <tr valign="baseline">
                  <td>
                    <b>Email:</b></td>
                  <td>
                    <input type="text" name="email" value="<? echo $email; ?>" size="40">
                  </td>
                </tr>
                <tr>
                  <td>&nbsp;</td>
                  <td>
                    <input type="submit" value="Best&auml;tigungsemail zusenden">
                    <input type="hidden" name="sendemailverify" value="yes">
                    <input type="hidden" name="loginwer" value="<? echo $loginwer; ?>">
                  </td>
                </tr>
              </table>
            </form>
            <? } else {?>
            <? if ($fehler=="yes") echo "<br>".$language["strLoginFehler"]; ?>
            <? if ($passwdfalsch=="yes") echo "<font color=\"red\" class=\"toppraktika\"><br>".$language["strpasswdfalsch"]."</font>" ?>
            <? if ($gesperrt=="yes") echo "<font color=\"red\" class=\"toppraktika\"><br>".$language["strGesperrt"]."</font>" ?>
            <? if ($keinlogin=="yes") echo "<font color=\"red\" class=\"toppraktika\"><br>".$language["strKeinLogin"]."</font>" ?>
            <? if ($loginleer=="yes") echo "<font color=\"red\" class=\"toppraktika\"><br>".$language["strLoginleer"]."</font>" ?>
            <? if ($passwortleer=="yes") echo "<font color=\"red\" class=\"toppraktika\"><br>".$language["strPasswortleer"]."</font>" ?>
            <P><font class="toppraktika"><? echo $language["strLoginHilfe"]; ?></font>
            <form action="./" method="post">
              <table border="0" width="252">
                <tr valign="baseline">
                  <td>
                    <pre><b><? echo $language["strLogin"]; ?></b></pre>
                  </td>
                  <td>
<?
if ($c_lid) $loginidemail=$c_lid;
if (!$c_lid) $loginidemail=$loginidemail;
?>
                    <input type="text" name="loginidemail" value="<? echo $loginidemail; ?>">
                  </td>
                </tr>
                <tr valign="baseline">
                  <td>
                    <pre><b><? echo $language["strPasswort"]; ?></b></pre>
                  </td>
                  <td>
                    <input type="password" name="passwort">
                  </td>
                </tr>
                <tr valign="baseline">
                  <td>&nbsp;</td>
                  <td>
                    <a href="<? echo $passwdpfad; ?>" onMouseOver="return Describe('<? echo $language["strZur"]; ?>')" onMouseOut="return Describe('')" onClick="windowanm=window.open('<? echo $passwdpfad; ?>','messageWindow','scrollbars=yes,statusbar=no,toolbar=no,width=515,height=480'); return false;"><? echo $language["strPasswortVergessen"]; ?></a><br><br>
                  </td>
                </tr>
                <tr>
                  <td>&nbsp;</td>
                  <td>
                    <input type="submit" value="<? echo $language["strEinloggen"]; ?>">
                    <input type="hidden" name="send" value="yes">
                    <input type="hidden" name="loginwer" value="<? echo $loginwer; ?>">
                  </td>
                </tr>
              </table>
            </form><? } ?>
      </table>
<? bodyoff(session_id(), session_name()); ?>