<?php
/* $miniwindow = true;
 $pointcount = 15;

 $noadvertise="yes";
*/
require_once("/home/praktika/etc/config.inc.php"); 

pageheader();
?>
<h3>Passwortabfrage</h3>

<form action="" method="post">
<fieldset>
<p><label for="loginidemail3">Login:</label><input type="text" id="loginidemail3" name="loginidemail" /></p>
<p><input type="submit" name="send" value="Absenden" /></p>
</fieldset>
</form>
<?php 
	bodyoff(); 
?>