<?
if(!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') {
	require_once('/home/praktika/etc/gb_config.inc.php');
} else {
	require_once('/home/praktika/etc/config.inc.php');	
}


if (!isset($_SESSION['s_loggedin']) || $_SESSION['s_loggedin'] == false) {
	header('Location: http://'.$_SERVER['HTTP_HOST'].'/login');
}

if($_POST["act"] == "delete") {
	$select = mysql_db_query($database_bprofil,'SELECT * FROM profil_beruferfahrung WHERE nutzerid='.$_SESSION['s_loginid'].' AND sprachid='.$_SESSION['s_sprachid'],$praktdbmaster);
	if (mysql_num_rows($select) > 0) {
		$profil = mysql_fetch_array($select);
		$schularray = wddx_deserialize($profil['berufserfahrungsarray']);
		$schularray = ($schularray);
	}	
	
	$reOrder = false;
	for($a = 0;$a < count($schularray);$a++) {
		if($a == $_POST["id"]) {
			$reOrder = true;
			unset($schularray[$a]);	
		}
	}
	
	if($reOrder) {
		$result = array();
		foreach ($schularray as $key => $value) {
			$result[] = $schularray[$key];
		}
		$schularray = $result;
	}
	
	$beruf = addslashes((wddx_serialize_value($schularray)));

	$updatestring = 'UPDATE profil_beruferfahrung SET sprachid=\''.$_SESSION['s_sprachid'].'\', berufserfahrungsarray=\''.$beruf.'\', modify=NOW() WHERE nutzerid='.$_SESSION['s_loginid'].' AND sprachid='.$_SESSION['s_sprachid'];

	Praktika_Lebenslauf::deleteCache();
	mysql_query($updatestring, $praktdbmaster);
	
	echo "delete";
	exit();
}

$_SESSION['restricted'] = RESTRICTED_CANDIDATE;
$_SESSION['current_user_group'] = USER_GROUP_CANDIDATES;
$_SESSION['current_page'] = PAGE_CV;

if ($_SESSION['s_sprachid'] == 2) {
	$lang["headline"]= 'Profil zur Berufserfahrung';
	$lang["variable1"]= 'Ihre bisherige berufliche T&auml;tigkeit';
	$lang["variable2"]= 'Zeitraum (von)';
	$lang["variable22"]= 'Zeitraum (bis)';
	$lang["variable3"]= 'T&auml;tigkeit als';
	$lang["variable4"]= 'im Unternehmen';
	$lang["variable5"]= 'BITTE W&Auml;HLEN';
	$lang["variable6"]= 'Beschreibung der T&auml;tigkeit';
	$lang["variable7"]= 'Berufsfeld';
	$lang["variable8"]= 'Ort';
	$lang["variable9"]= 'Monat';
	$lang["variable10"]= 'Jahr';
	$lang["variable11"]= 'Land';
	$lang["variableb1"]= 'Speichern';
	$lang["variableb2"]= 'Vorschau';
	$lang["variableb3"]= 'zur&uuml;cksetzen';
	$lang["variableb4"]= 'zur &Uuml;bersicht';
	$lang["text1"]= 'Bewerberprofil in';
	$lang["text2"]= 'Anzahl der Eintr&auml;ge';
	$lang["text3"]= 'Hier werden die Daten &uuml;ber Ihre beruflichen Erfahrungen erfa&szlig;t.';
	$lang["text4"]= 'Ihr Eintrag wurde gespeichert!';
	$lang["text5"]= 'Baustein';
	$lang["text6"]= 'von';
	$lang["giftext"]= 'Vorschau Lebenslauf!';
	$lang["myaccount"]= 'Mein Account';
	$lang["lebenslaufprofil"]= 'zum Profil';
	$lang["bisJetzt"] = "Bis Jetzt";	
} elseif ($_SESSION['s_sprachid'] == 1) {
	$lang["headline"]= 'Professional Experience Profile';
	$lang["variable1"]= 'Professional Experience';
	$lang["variable2"]= 'From m/y';
	$lang["variable22"]= 'To m/y';
	$lang["variable3"]= 'Position';
	$lang["variable4"]= 'Company';
	$lang["variable5"]= 'PLEASE CHOOSE';
	$lang["variable6"]= 'Description';
	$lang["variable7"]= 'Occupational Field';
	$lang["variable8"]= 'City Location';
	$lang["variable9"]= 'Month';
	$lang["variable10"]= 'Year';
	$lang["variable11"]= 'Country';
	$lang["variableb1"]= 'Speichern';
	$lang["variableb2"]= 'Preview';
	$lang["variableb3"]= 'Reset';
	$lang["variableb4"]= 'Main Menu';
	$lang["text1"]= 'Profile in';
	$lang["text2"]= 'choose number of forms below';
	$lang["text3"]= 'Here you can describe your experience.';
	$lang["text4"]= 'Your entry has been saved!';
	$lang["text5"]= 'Part';
	$lang["text6"]= 'of';
	$lang["giftext"]= 'preview resume!';
	$lang["myaccount"]= 'my account';
	$lang["lebenslaufprofil"]= 'profile';
	$lang["bisJetzt"] = "present";	
}

function getEntryForm($number, $values=array()) {
	global $lang;
	$i = $number;
	
	$land = Praktika_Listen::getLand();
	
	$results =  '			<br /><h4>'.$lang["variable1"].($number > 0?' &nbsp;&nbsp;<span onclick="lebenslauf.deleteRow('.$i.',\'schulausbildung_\');" class="abschnittEntfernen" style="color:#aaa; font-size:10px;">(Abschnitt entfernen)</span>':'')."</h4>\n";
	$results .= '			<fieldset>';
	$results .= '				<p>'."\n";
	$results .= '					<label for="submitarray_'.$i.'_mvon">'.$lang["variable2"].'</label>'."\n";
	$results .= '					<select id="submitarray_'.$i.'_mvon" name="submitarray['.$i.'][mvon]" class="month html_controlled">'."\n";
	$results .= '						<option value="">--</option>'."\n";
	$j = 1;
	while ($j < 13) {
		$results .= '						<option ';
		if (isset($values['mvon']) && $j == $values['mvon']) {
			$results .= 'selected="selected" ';
		}
		$results .= 'value="'.$j.'">'.sprintf("%02.0f",$j).'</option>'."\n";
		$j++;
	}
	$results .= '					</select> / '."\n";
	$results .= '					<select id="submitarray_'.$i.'_jvon" name="submitarray['.$i.'][jvon]" class="year html_controlled">'."\n";
	$results .= '						<option value="">--</option>'."\n";
	$j = (date('Y') - 53);
	while ($j <= date('Y')) {
		$results .= '						<option ';
		if (isset($values['jvon']) && $j == $values['jvon']) {
			$results .= 'selected="selected" ';
		}
		$results .= 'value="'.$j.'">'.sprintf("%02.0f",$j).'</option>'."\n";
		$j++;
	}
	$results .= '					</select>'."\n";
	$results .= '				</p>'."\n";
	$results .= '				<p>'."\n";
	$results .= '					<label for="submitarray_'.$i.'_mbis">'.$lang["variable22"].'</label>'."\n";
	$results .= '					<select id="submitarray_'.$i.'_mbis" name="submitarray['.$i.'][mbis]" class="month html_controlled">'."\n";
	$results .= '						<option value="">--</option>'."\n";
	$j = 1;
	while ($j < 13) {
		$results .= '						<option ';
		if (isset($values['mbis']) && $j == $values['mbis']) {
			$results .= 'selected="selected" ';
		}
		$results .= 'value="'.$j.'">'.sprintf("%02.0f",$j).'</option>'."\n";
		$j++;
	}
	$results .= '					</select> / '."\n";
	$results .= '					<select id="submitarray_'.$i.'_jbis" name="submitarray['.$i.'][jbis]" class="year html_controlled">'."\n";
	$results .= '						<option value="">--</option>'."\n";
	$j = (date('Y') - 53);
	while ($j <= date('Y')) {
		$results .= '						<option ';
		if (isset($values['jbis']) && $j == $values['jbis']) {
			$results .= 'selected="selected" ';
		}
		$results .= 'value="'.$j.'">'.sprintf("%02.0f",$j).'</option>'."\n";
		$j++;
	}
	$results .= '					</select>'."\n";
	$results .=  '					<input class=" html_controlled" type="checkbox" value="true" name="submitarray['.$i.'][toPresent]" '.($values["toPresent"]=="true"?"checked='checked'":"").'> '.$lang["bisJetzt"]."\n";
	$results .= '				</p>'."\n";
	$results .= '				<p>'."\n";
	$results .= '					<label for="submitarray_'.$i.'_beruf">'.$lang["variable3"].'</label><input id="submitarray_'.$i.'_beruf" name="submitarray['.$i.'][beruf]" value="'.(isset($values['beruf']) ? $values['beruf'] : '').'" />'."\n";
	$results .= '				</p>'."\n";
	$results .= '				<p>'."\n";
	$results .= '					<label for="submitarray_'.$i.'_unternehmen">'.$lang["variable4"].'</label><input id="submitarray_'.$i.'_unternehmen" name="submitarray['.$i.'][unternehmen]" value="'.(isset($values['unternehmen']) ? $values['unternehmen'] : '').'" />'."\n";
	$results .= '				</p>'."\n";
	$results .= '				<p>'."\n";
	$results .= '					<label for="submitarray_'.$i.'_ort">'.$lang["variable8"].'</label><input id="submitarray_'.$i.'_ort" name="submitarray['.$i.'][ort]" value="'.(isset($values['ort']) ? $values['ort'] : '').'" />'."\n";
	$results .= '				</p>'."\n";
	$results .= '				<p>'."\n";
	$results .= '					<label for="submitarray_'.$i.'_land">'.$lang["variable11"].'</label>'."\n";
	$results .= '					<select id="submitarray_'.$i.'_land" class=" html_controlled" name="submitarray['.$i.'][land]">'."\n";
	$results .= '						<option value="0">'.$lang["variable5"].'</option>'."\n";
	$j=0;
	for($a = 0;$a < count($land);$a++) {
		$html = ($land[$a]["title"]);
		$results .= '						<option ';
		if  (isset($values['land']) && $land[$a]["id"] == $values['land']) {
			$results .= 'selected="selected" ';
		}
		$results .= 'value="'.$land[$a]["id"].'">'.$html.'</option>'."\n";
		$j++;
	}
	$results .= ' 					</select>'."\n";
	$results .= '				</p>'."\n";
	$results .= '				<p>'."\n";
	$results .= '					<label for="submitarray_'.$i.'_taetigkeit">'.$lang["variable6"].'</label><textarea id="submitarray_'.$i.'_taetigkeit" name="submitarray['.$i.'][taetigkeit]" rows="10" cols="16">'.(isset($values['taetigkeit']) ? stripslashes($values['taetigkeit']) : '').'</textarea>'."\n";
	$results .= '				</p>'."\n";
	$results .= '			</fieldset>'."\n";

	return $results;
}

if($_POST["act"] == "newentry") {

	echo getEntryForm((int)$_POST["number"]);
		
	exit();
}


pageheader(array('page_title' => $lang["headline"], 'externScripts' => array("/scripts/ajax/lebenslauf.js", "/scripts/microajax.js")));
?>
<script type="text/javascript" src="/scripts/ajax/lebenslauf.js"></script>
<script type="text/javascript" src="/scripts/microajax.js"></script>
<?
if (isset($_POST['save'])) {
	$select = mysql_db_query($database_bprofil,'SELECT id FROM profil_beruferfahrung WHERE nutzerid='.$_SESSION['s_loginid'].' AND sprachid='.$_SESSION['s_sprachid'],$praktdbmaster);

	if (mysql_num_rows($select) <1) {
		$insertstring = 'INSERT INTO profil_beruferfahrung (nutzerid, sprachid, datum_eintrag, modify) VALUES (\''.$_SESSION['s_loginid'].'\', \''.$_SESSION['s_sprachid'].'\', NOW(), NOW())';
		mysql_db_query($database_bprofil,$insertstring,$praktdbmaster);
	}
	$reOrder = false;
	for($a = 0;$a < count($_POST["submitarray"]);$a++) {
		if($_POST["submitarray"][$a]["toPresent"] == "true") {
			$_POST["submitarray"][$a]["mbis"] = "";
			$_POST["submitarray"][$a]["jbis"] = "";
		}			
		if($_POST["submitarray"][$a]["delete"] == "1") {
			$reOrder = true;
			unset($_POST["submitarray"][$a]);	
		}
	}
	
	if($reOrder) {
		$result = array();
		foreach ($_POST["submitarray"] as $key => $value) {
			$result[] = $_POST["submitarray"][$key];
		}
		$_POST["submitarray"] = $result;
	}	

	$beruf = addslashes((wddx_serialize_value($_POST['submitarray'])));
	$updatestring = 'UPDATE profil_beruferfahrung SET sprachid=\''.$_SESSION['s_sprachid'].'\', berufserfahrungsarray=\''.$beruf.'\', modify=NOW() WHERE nutzerid='.$_SESSION['s_loginid'].' AND sprachid='.$_SESSION['s_sprachid'];
	
	
	mysql_db_query($database_bprofil,$updatestring,$praktdbmaster);
	recalc_profilquali();
	Praktika_Lebenslauf::deleteCache();	
	
	if($_POST["backToStart"] == "1") {
		$_SESSION["backToStart"] = "1";
		header("Location: /lebenslauf/ok/");
	} else {
		$_SESSION["backToStart"] = "0";
	}
}

$select = mysql_db_query($database_bprofil,'SELECT * FROM profil_beruferfahrung WHERE nutzerid='.$_SESSION['s_loginid'].' AND sprachid='.$_SESSION['s_sprachid'],$praktdbmaster);
if (mysql_num_rows($select) > 0) {
	$profil = mysql_fetch_array($select);
	$berufsarray = wddx_deserialize($profil['berufserfahrungsarray']);
	$berufsarray = ($berufsarray);
}

if(isset($berufsarray)) {
	$anzahl = count($berufsarray);
} else {
	$anzahl = 1;
}

#$anzahl = (!isset($berufsarray) || count($berufsarray) == 0) ? 1 : count($berufsarray);
#$anzahl = (isset($_POST['anzahl']) && intval($_POST['anzahl']) > $anzahl) ? intval($_POST['anzahl']) : $anzahl;

echo '<div id="recruitingCenter">';

$parts = array("lebenslauf");
include(SERVER_ROOT."/public_html/home/praktikanten/kcenter/navi.php");

#language_select($text1);
# echo '		<br /><p>'.$lang["text3"].'</p>'."\n";
echo '		<form id="contentform" action="http://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'].'" method="post">'."\n";
echo '			<fieldset id="anz_fieldsets">'."\n";
echo '				<label for="anzahl">'.$lang["text2"].'</label>'."\n";
echo '				<select id="anzahl" name="anzahl" class="html_controlled" onchange="submit();">'."\n";

$i = 1;
while ($i < 11) {
	echo '					<option ';
	if ($i == $anzahl) {
		echo 'selected="selected" ';
	}
	echo 'value="'.$i.'">'.$i.'</option>'."\n";
	$i++;
}
echo '				</select>'."\n";
echo '			</fieldset>'."\n";

if (isset($_POST['save'])) {
	echo '			<p class="hint success">'.$lang["text4"].'</p>'."\n";
}

$lander = 
$land = mysql_db_query($database_db,'SELECT '.$_SESSION['s_sprache'].', id FROM land ORDER BY '.$_SESSION['s_sprache'].'',$praktdbslave);
$anz_land = mysql_num_rows($land);

$i=0;
while ($i < $anzahl) {
	echo getEntryForm($i, $berufsarray[$i]);

	$i++;
}
?>
<script type="text/javascript">
	$('#anz_fieldsets').css("display", "none");
	var countEntries = <?=$anzahl ?>;
</script>
<div id="extraContent">
	
</div>
<br />
<div style="text-align:center;">
	<a href='#' onclick='lebenslauf.addEntry(); return false;'>Abschnitt hinzuf&uuml;gen</a>
</div><br />
<?
echo '			<fieldset class="control_panel">'."\n";
echo '				<p class="center">'."\n";
echo '					<a class="button alternative small" href="#" onclick="lebenslauf.addEntry(); return false;">Abschnitt hinzuf&uuml;gen</a>'."\n";
echo '				</p>'."\n";
echo '				<br />'."\n";
echo '				<p class="center"><input class="button small" type="submit" value="'.$lang["variableb1"].'" name="save" /></p>'."\n";
echo '				<p><label for="backToStart" class="komplette_breite"><input type="checkbox" class="html_controlled" name="backToStart" id="backToStart" value="1" '.(!isset($_SESSION["backToStart"]) || (isset($_SESSION["backToStart"]) && $_SESSION["backToStart"] != "1")?'':'checked="checked"').' /> Nach dem Speichern zur&uuml;ck zur Lebenslauf&uuml;bersicht</label></p>';
echo '			</fieldset>'."\n";
echo '		</form>'."\n";
echo '	</div>'."\n";

bodyoff();
?>