<?php
if(!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') {
	require_once('/home/praktika/etc/gb_config.inc.php');
} else {
	require_once('/home/praktika/etc/config.inc.php');	
}

if (!isset($_SESSION['s_loggedin']) || $_SESSION['s_loggedin'] == false) {
	header('Location: http://'.$_SERVER['HTTP_HOST'].'/login');
}

if($_POST["act"] == "delete") {
	$select = $hDB->query('SELECT * FROM prakt2_bprofil.profil_schule WHERE nutzerid='.$_SESSION['s_loginid'].' AND sprachid='.$_SESSION['s_sprachid'],$praktdbmaster);
	if (mysql_num_rows($select) > 0) {
		$profil = mysql_fetch_array($select);
		$schularray = wddx_deserialize($profil['schularray']);
		$schularray = Praktika_String::getUtf8String_Array($schularray);
	}	
	
	$reOrder = false;
	for($a = 0;$a < count($schularray);$a++) {
		if($a == $_POST["id"]) {
			$reOrder = true;
			unset($schularray[$a]);	
		}
	}

	if($reOrder) {
		$result = array();
		foreach ($schularray as $key => $value) {
			$result[] = $schularray[$key];
		}
		$schularray = $result;
	}
	
	$schule = wddx_serialize_value($schularray);

	$updatestring = 'UPDATE prakt2_bprofil.profil_schule SET sprachid='.$_SESSION['s_sprachid'].', schularray=\''.mysql_real_escape_string($schule).'\', modify=NOW() WHERE nutzerid='.$_SESSION['s_loginid'].' AND sprachid='.$_SESSION['s_sprachid'];

	$hDB->query($updatestring, $praktdbmaster);
	
	Praktika_Lebenslauf::deleteCache();	
	exit();
}

$_SESSION['restricted'] = RESTRICTED_CANDIDATE;
$_SESSION['current_user_group'] = USER_GROUP_CANDIDATES;
$_SESSION['current_page'] = PAGE_CV;

		  $monate = array(1=>"Januar",
		                  2=>"Februar",
		                  3=>"M&auml;rz",
		                  4=>"April",
		                  5=>"Mai",
		                  6=>"Juni",
		                  7=>"Juli",
		                  8=>"August",
		                  9=>"September",
		                  10=>"Oktober",
		                  11=>"November",
		                  12=>"Dezember");	
						  
if ($_SESSION['s_sprachid'] == 2) {
	$lang["headline"] = 'Profil zur Schulausbildung';
	$lang["variable1"] = 'Schulausbildung';
	$lang["variable2"] = 'Zeitraum (von)';
	$lang["variable22"] = 'Zeitraum (bis)';
	$lang["variable3"] = 'Schule';
	$lang["variable4"] = 'erreichter Schulabschluss';
	$lang["variable5"] = 'Ergebnis';
	$lang["variable6"] = 'Monat';
	$lang["variable7"] = 'Jahr';
	$lang["variable8"] = 'Ort';
	$lang["variable9"] = 'Land';
	$lang["variableb1"] = 'Speichern';
	$lang["variableb2"] = 'Vorschau';
	$lang["variableb3"] = 'zur&uuml;cksetzen';
	$lang["variableb4"] = 'zur &Uuml;bersicht';
	$lang["text1"] = 'Bewerberprofil in';
	$lang["text2"] = 'Anzahl der Eingabemasken';
	$lang["text3"] = 'Hier werden die Daten &uuml;ber Ihren schulischen Werdegang erfa&szlig;t.';
	$lang["text4"] = 'Ihr Eintrag wurde gespeichert!';
	$lang["text5"] = 'Baustein';
	$lang["text6"] = 'von';
	$lang["giftext"] = 'Vorschau Lebenslauf!';
	$lang["myaccount"] = 'Mein Account';
	$lang["lebenslaufprofil"] = 'zum Profil';
	$lang["delete_entry"] = "Abschnitt entfernen";
	$lang["bisJetzt"] = "Bis Jetzt";
} elseif ($_SESSION['s_sprachid'] == 1) {
	$lang["headline"] = 'Education Profile';
	$lang["variable1"] = 'School';
	$lang["variable2"] = 'From m/y';
	$lang["variable22"] = 'To m/y';
	$lang["variable3"] = 'Schoolname';
	$lang["variable4"] = 'Degree/Level Attaired';
	$lang["variable5"] = 'Result';
	$lang["variable6"] = 'Month';
	$lang["variable7"] = 'Year';
	$lang["variable8"] = 'City';
	$lang["variable9"] = 'Country';
	$lang["variableb1"] = 'Speichern';
	$lang["variableb2"] = 'Preview';
	$lang["variableb3"] = 'Reset';
	$lang["variableb4"] = 'Main Menu';
	$lang["text1"] = 'Profile in';
	$lang["text2"] = 'choose number of forms below';
	$lang["text3"] = 'The information about your schoolastic career will be stored here.';
	$lang["text4"] = 'Your entry has been saved!';
	$lang["text5"] = 'Part';
	$lang["text6"] = 'of';
	$lang["giftext"] = 'preview resume!';
	$lang["myaccount"] = 'my account';
	$lang["lebenslaufprofil"] = 'profile';
	$lang["delete_entry"] = "remove segment";
	$lang["bisJetzt"] = "present";
}
function stripslashes_array($array) {
    $return = array();
    foreach ($array as $key => $value) {
        $return[$key] = stripslashes($value);
    }
    return $return;
}
function getEntryForm($number, $values=array()) {
	global $lang, $monate;

	$values = Praktika_String::stripslashes($values);

	# $values = stripslashes_array($values);
	$i = $number;
	$return = "";
	$return =  '			<br /><h4>'.$lang["variable1"].($number > 0?' &nbsp;&nbsp;<span onclick="lebenslauf.deleteRow('.$i.',\'schulausbildung_\');" class="abschnittEntfernen" style="color:#aaa; font-size:10px;">(Abschnitt entfernen)</span>':'')."</h4>\n";
	$return .= '			<fieldset>';
	$return .= '				<p>'."\n";
	$return .= '					<label for="submitarray_'.$i.'_mvon">'.$lang["variable2"].'</label>'."\n";
	$return .=  '					<select id="submitarray_'.$i.'_mvon" name="submitarray['.$i.'][mvon]" class="month html_controlled">'."\n";
	$return .= '						<option value="">--</option>'."\n";
	
	$j = 1;
	while ($j < 13) {
		$return .=  '						<option ';
		if (isset($values['mvon']) && $j == $values['mvon']) {
			$return .=  'selected="selected" ';
		}
		$return .=  'value="'.$j.'">'.sprintf("%02.0f",$j).'</option>'."\n";
		$j++;
	}
	$return .=  '					</select> / '."\n";
	$return .=  '					<select id="submitarray_'.$i.'_jvon" name="submitarray['.$i.'][jvon]" class="year html_controlled">'."\n";
	$return .=  '						<option value="">--</option>'."\n";
	$j = 1950;
	while ($j <= date('Y')) {
		$return .=  '						<option ';
		if (isset($values['jvon']) && $j == $values['jvon']) {
			$return .=  'selected="selected" ';
		}
		$return .=  'value="'.$j.'">'.sprintf("%02.0f",$j).'</option>'."\n";
		$j++;
	}
	$return .=  '					</select>'."\n";
	$return .=  '				</p>'."\n";
	$return .=  '				<p>'."\n";
	$return .=  '					<label for="submitarray_'.$i.'_mbis">'.$lang["variable22"].'</label>'."\n";
	$return .=  '					<select id="submitarray_'.$i.'_mbis" name="submitarray['.$i.'][mbis]" class="month html_controlled">'."\n";
	$return .=  '						<option value="">--</option>'."\n";
	$j = 1;
	while ($j < 13) {
		$return .=  '						<option ';
		if (isset($values['mbis']) && $j == $values['mbis']) {
			$return .=  'selected="selected" ';
		}
		$return .=  'value="'.$j.'">'.sprintf("%02.0f",$j).'</option>'."\n";
		$j++;
	}
	$return .=  '					</select> / '."\n";
	$return .=  '					<select id="submitarray_'.$i.'_jbis" name="submitarray['.$i.'][jbis]" class="year html_controlled">'."\n";
	$return .=  '						<option value="">--</option>'."\n";
	$j = date('Y') + 10;
	while ($j > 1950) {
		$return .=  '						<option ';
		if (isset($values['jbis']) && $j == $values['jbis']) {
			$return .=  'selected="selected" ';
		}
		$return .=  'value="'.$j.'">'.sprintf("%02.0f",$j).'</option>'."\n";
		$j--;
	}
	$return .=  '					</select> ';
	$return .=  '					&nbsp;&nbsp;<input class="html_controlled" type="checkbox" value="true" name="submitarray['.$i.'][toPresent]" '.($values["toPresent"]=="true"?"checked='checked'":"").'> '.$lang["bisJetzt"]."\n";
	$return .=  '				</p>'."\n";
	$return .=  '				<p>'."\n";
	$return .=  '					<label for="submitarray_'.$i.'_schule">'.$lang["variable3"].'</label><input id="submitarray_'.$i.'_schule" name="submitarray['.$i.'][schule]" value="'.(isset($values['schule']) ? $values['schule'] : '').'" />'."\n";
	$return .=  '				</p>'."\n";
	$return .=  '				<p>'."\n";
	$return .=  '					<label for="submitarray_'.$i.'_ort">'.$lang["variable8"].'</label><input id="submitarray_'.$i.'_ort" name="submitarray['.$i.'][ort]" value="'.(isset($values['ort']) ? $values['ort'] : '').'" />'."\n";
	$return .=  '				</p>'."\n";
	$return .=  '				<p>'."\n";
	$return .=  '					<label for="submitarray_'.$i.'_land">'.$lang["variable9"].'</label><input id="submitarray_'.$i.'_land" name="submitarray['.$i.'][land]" value="'.(isset($values['land']) ? $values['land'] : '').'" />'."\n";
	$return .=  '				</p>'."\n";
	$return .=  '				<p>'."\n";
	$return .=  '					<label for="submitarray_'.$i.'_abschluss">'.$lang["variable4"].'</label><input id="submitarray_'.$i.'_abschluss" name="submitarray['.$i.'][abschluss]" value="'.(isset($values['abschluss']) ? $values['abschluss'] : '').'" />'."\n";
	$return .=  '				</p>'."\n";
	$return .=  '				<p>'."\n";
	$return .=  '					<label for="submitarray_'.$i.'_ergebnis">'.$lang["variable5"].'</label><input id="submitarray_'.$i.'_ergebnis" name="submitarray['.$i.'][ergebnis]" value="'.(isset($values['ergebnis']) ? $values['ergebnis'] : '').'" />'."\n";
	$return .=  '				</p>'."\n";
	$return .=  '			</fieldset></span>'."\n";	
	
	return $return;
}

if($_POST["act"] == "newentry") {

	echo getEntryForm((int)$_POST["number"]);
		
	exit();
}

if (isset($_POST['save'])) {
	$sql = sprintf("SELECT 
						id 
					FROM 
						".$database_bprofil.".profil_schule
					WHERE 
						nutzerid = %1\$d AND
						sprachid = %2\$d;",
					$_SESSION['s_loginid'],
					$_SESSION['s_sprachid']);
	$select = $hDB->query($sql, $praktdbmaster);

	if (mysql_num_rows($select) < 1) {
		$insertstring = 'INSERT INTO '.$database_bprofil.'.profil_schule (nutzerid, sprachid, datum_eintrag, modify) VALUES ('.$_SESSION['s_loginid'].', '.$_SESSION['s_sprachid'].', NOW(), NOW())';
		$hDB->query($insertstring,$praktdbmaster);
	}
	
	$reOrder = false;
	for($a = 0;$a < count($_POST["submitarray"]);$a++) {
		if($_POST["submitarray"][$a]["toPresent"] == "true") {
			$_POST["submitarray"][$a]["mbis"] = "";
			$_POST["submitarray"][$a]["jbis"] = "";
		}
		if($_POST["submitarray"][$a]["delete"] == "1") {
			$reOrder = true;
			unset($_POST["submitarray"][$a]);	
		}
	}
	
	if($reOrder) {
		$result = array();
		foreach ($_POST["submitarray"] as $key => $value) {
			$result[] = $_POST["submitarray"][$key];
		}
		$_POST["submitarray"] = $result;
	}
	
	
	foreach ($_POST['submitarray'] as $key => $record)
	{
		if (empty($record['schule']))
		{
			array_splice($_POST['submitarray'], $key, 1);
		}
	}

	# Praktika_String::addslashes($_POST['submitarray']);
	
	$schule = mysql_real_escape_string(wddx_serialize_value($_POST['submitarray']));

	$updatestring = 'UPDATE '.$database_bprofil.'.profil_schule SET sprachid='.$_SESSION['s_sprachid'].', schularray=\''.$schule.'\', modify=NOW() WHERE nutzerid='.$_SESSION['s_loginid'].' AND sprachid='.$_SESSION['s_sprachid'];

	$hDB->query($updatestring,$praktdbmaster);
	recalc_profilquali();
	Praktika_Lebenslauf::deleteCache();	
	
	if($_POST["backToStart"] == "1") {
		$_SESSION["backToStart"] = "1";
		header("Location: /lebenslauf/ok/");
	} else {
		$_SESSION["backToStart"] = "0";
	}
}

$select = $hDB->query('SELECT * FROM '.$database_bprofil.'.profil_schule WHERE nutzerid='.$_SESSION['s_loginid'].' AND sprachid='.$_SESSION['s_sprachid'],$praktdbmaster);
if (mysql_num_rows($select) > 0) {
	$profil = mysql_fetch_array($select);
	$schularray = wddx_deserialize($profil['schularray']);
	$schularray = Praktika_String::getUtf8String_Array($schularray);
}

if(isset($schularray)) {
	$anzahl = count($schularray);
} else {
	$anzahl = 1;
}

pageheader(array('page_title' => $lang["headline"], 'externScripts' => array("/scripts/ajax/lebenslauf.js", "/scripts/microajax.js")));
?>
<script type="text/javascript" src="/scripts/ajax/lebenslauf.js"></script>
<script type="text/javascript" src="/scripts/microajax.js"></script>
<?
echo '<div id="recruitingCenter">';

$parts = array("lebenslauf");
include(SERVER_ROOT."/public_html/home/praktikanten/kcenter/navi.php");

echo '		<form id="contentform" action="http://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'].'" method="post">'."\n";
echo '			<fieldset id="anz_fieldsets">'."\n";
 echo '				<label for="anzahl">'.$lang["text2"].'</label>'."\n";
 echo '				<select id="anzahl" class="html_controlled" name="anzahl" onchange="submit();">'."\n";

$i = 1;
while ($i < 11) {
	echo '					<option ';
	if ($i == $anzahl) {
		echo 'selected="selected" ';
	}
	echo 'value="'.$i.'">'.$i.'</option>'."\n";
	$i++;
}
echo '				</select>'."\n";
echo '			</fieldset>'."\n";

if (isset($_POST['save'])) {
	echo '			<p class="hint success">'.$lang["text4"].'</p>'."\n";
}

$qualifikationen = $hDB->query('SELECT qualifikation, id FROM '.$database_db.'.qualifikation ORDER BY folge',$praktdbslave);
$anz_qualifikationen = mysql_num_rows($qualifikationen);
?>
<script type="text/javascript">
	$('#anz_fieldsets').css("display","none");
	var countEntries = <?=$anzahl ?>;
</script>
<?
$i=0;
while ($i < $anzahl) {
	echo getEntryForm($i, $schularray[$i]);

	$i++;
} 
?>
<div id="extraContent"></div>
<br />
<br />
<?
echo '			<fieldset class="control_panel">'."\n";
echo '				<p class="center">'."\n";
echo '					<a class="button alternative small" href="#" onclick="lebenslauf.addEntry(); return false;">Abschnitt hinzuf&uuml;gen</a>'."\n";
echo '				</p>'."\n";
echo '				<br />'."\n";
echo '				<p class="center"><input class="button small" type="submit" value="'.$lang["variableb1"].'" name="save" /></p>'."\n";
echo '				<p><label for="backToStart" class="komplette_breite"><input type="checkbox" class="html_controlled" name="backToStart" id="backToStart" value="1" '.(!isset($_SESSION["backToStart"]) || (isset($_SESSION["backToStart"]) && $_SESSION["backToStart"] != "1")?'':'checked="checked"').' /> Nach dem Speichern zur&uuml;ck zur Lebenslauf&uuml;bersicht</label></p>';
echo '			</fieldset>'."\n";
echo '		</form>'."\n";
echo '	</div>'."\n";

# echo $_SERVER["SERVER_ADDR"];
bodyoff();
?>