<?php
$sprachbasisdatei = "/home/praktikanten/einblick.phtml";
ini_set('display_errors', '1');
require("/home/praktika/etc/config.inc.php");

$_SESSION['current_user_group'] = USER_GROUP_CANDIDATES;
$_SESSION['current_page'] = PAGE_SEARCH;
$_SESSION['sidebar'] = 'default';
$pointcount = "18";

pageheader(array('page_title' => 'Suche nach Unternehmen'));
?>

<script type="text/javascript" src="/scripts/ajax/search.js"></script>
<link type="text/css" media="screen,print" rel="stylesheet" href="/styles/v2/suche.css" />

<?php
if (!$firmen = $zCache->load('unternehmenssuche')) {
	
	$sql = '	SELECT
					firmen.id,
					firma
				FROM
					firmen
					LEFT JOIN firmen_prop_assign AS fpa ON fpa.firmenid = firmen.id
				WHERE
					fpa.firmenlevel > 0';
					
	$result = mysql_query($sql, $praktdbslave);
	$firmen = array();
	
	while ($row = mysql_fetch_assoc($result)) {
		$firmen[strtoupper($row['firma'][0])][] = array($row['id'], $row['firma']);
	}
	
	ksort($firmen);
	$zCache->save($firmen, 'unternehmenssuche', array(), 68000 * 7);
}

$rowBreak = intval(count($firmen) / 2) + 2;
?>

<ul style="float:left; width:350px; height:100%;">

<?php
$firstLetter = '';
$b = 0;

foreach ($firmen as $key => $value) {
	if (htmlentities($key) == 'L') {
		echo '</ul><ul style="margin-left: 320px;">' . "\n";
	}

	$b++;

	echo '<li class="katalogLetter"><strong>' . htmlentities($key) . '</strong></li>' . "\n";
		
	for ($a = 0; $a < count($value); $a++) {
		echo '<li><a href="/unternehmenssuche/' . intval($value[$a][0]) . '/' . urlencode(stripslashes($value[$a][1])) . '">' . htmlspecialchars(stripslashes($value[$a][1])) . '</a></li>' . "\n";
	}
}
?>

</ul>

<?php
$_SESSION['sidebar'] = '';
bodyoff();
?>