<?
// Kann weg (by stefan)
require("/home/praktika/etc/config.inc.php");

if (!isset($_SESSION['s_loggedin']) || $_SESSION['s_loggedin'] == false) {
	header('Location: http://'.$_SERVER['HTTP_HOST'].'/login');
}

$_SESSION['restricted'] = RESTRICTED_CANDIDATE;
$_SESSION['current_user_group'] = USER_GROUP_CANDIDATES;
$_SESSION['current_page'] = PAGE_MY_PRAKTIKA;

pageheader(array('page_title' => 'Eintrag Nebenjobgesuch'));

if (isset($_POST['senden']) &&
	isset($_POST['taetigkeit']) &&
	isset($_POST['beschreibungen']) &&
	isset($_POST['arbeitsort']) &&
	isset($_POST['verfall_tag']) &&
	isset($_POST['verfall_monat']) &&
	isset($_POST['verfall_jahr']) &&
	!empty($_POST['taetigkeit']) &&
	!empty($_POST['beschreibungen']) &&
	!empty($_POST['arbeitsort']) &&
	!empty($_POST['verfall_tag']) &&
	!empty($_POST['verfall_monat']) &&
	!empty($_POST['verfall_jahr'])) {
	
	/* datumsfelder zusammensetzen  */
	$datum_verfall = $_POST['verfall_jahr'].'-'.$_POST['verfall_monat'].'-'.$_POST['verfall_tag'];
	
	$branchenselect = mysql_db_query($database_db,'SELECT * FROM branchen WHERE '.$_SESSION['s_sprache'].' <> \'\' ORDER BY '.$_SESSION['s_sprache'],$praktdbslave);
	while ($row = mysql_fetch_array($branchenselect, MYSQL_ASSOC)) {
	   $branchen[$row['id']] = $row[$_SESSION['s_sprache']];
	}
	
	if (isset($_POST['branche']) && is_array($_POST['branche'])) {
		$branchetext = array();
		foreach ($_POST['branche'] as $brancheitem) {
			$branchetext[] = $branchen[$brancheitem];
		}
	} else {
		$_POST['branche'] = array();
		$branchetext = array();
	}
	
	$insertstring = 'REPLACE INTO nebenjobgesuch (
						'.((isset($_POST['gesuch']) && !empty($_POST['gesuch'])) ? 'id,' : '').'
						inactive,
						nutzerid,
						taetigkeit,
						berufsfeld,
						zeitraum_ab_m,
						zeitraum_ab_y,
						zeitraum,
						beschreibung,
						qualifikation,
						sonst_qualifikation,
						branchen,
						branchentext,
						arbeitsort,
						einsatzland,
						kenntnisse,
						vorh_unternehmen,
						sprachkenntnisse1,
						sprachkenntnisse2,
						sprachkenntnisse3,
						host,
						ip,
						datum_eintrag,
						datum_verfall,
						modify
					) VALUES (
						'.((isset($_POST['gesuch']) && !empty($_POST['gesuch'])) ? intval($_POST['gesuch']).',' : '').'
						\'false\',
						'.intval($_SESSION['s_nutzerid']).',
						\''.mysql_real_escape_string($_POST['taetigkeit']).'\',
						'.intval($_POST['berufsfeld']).',
						'.intval($_POST['zeitraum_ab_m']).',
						'.intval($_POST['zeitraum_ab_y']).',
						\''.mysql_real_escape_string($_POST['zeitraum']).'\',
						\''.mysql_real_escape_string($_POST['beschreibungen']).'\',
						'.intval($_POST['qualifikation']).',
						\''.mysql_real_escape_string($_POST['sonst_qualifikation']).'\',
						\''.implode(',',$_POST['branche']).'\',
						\''.implode(' ',$branchetext).'\',
						\''.mysql_real_escape_string($_POST['arbeitsort']).'\',
						'.intval($_POST['einsatzland']).',
						\''.mysql_real_escape_string($_POST['kenntnisse']).'\',
						\''.mysql_real_escape_string($_POST['vorh_unternehmen']).'\',
						'.intval($_POST['sprachkenntnisse1']).',
						'.((isset($_POST['sprachkenntnisse2']) && !empty($_POST['sprachkenntnisse2'])) ? intval($_POST['sprachkenntnisse2']) : 'NULL').',
						'.((isset($_POST['sprachkenntnisse3']) && !empty($_POST['sprachkenntnisse3'])) ? intval($_POST['sprachkenntnisse2']) : 'NULL').',
						\''.$host.'\',
						\''.$ip.'\',
						NOW(),
						\''.$datum_verfall.'\',
						NOW()
					)';
	//echo $insertstring;
	/* datensatz einfuegen */
	mysql_db_query($database_db,$insertstring,$praktdbmaster);
	
	/* id bestimmen */
	$insert_id = mysql_insert_id($praktdbmaster);
	
	/* Logfile eintragen */
	$fp = fopen($logfile, 'a');
	fputs($fp, $insertstring);
	fputs($fp, "\n");
	fclose($fp);
	
	/* infomail zusammenbauen */
	$subject = 'praktika.de NUTZER-Eintrag Nebenjobgesuch: ID: '.$insert_id;
	$mailstring = 'NEBENJOBGESUCH - EINTRAG'."\n\n";
	$mailstring = $mailstring.'ID: '.$insert_id."\n\n";
	$mailstring = $mailstring.'Taetigkeit: '.$_POST['taetigkeit']."\n";
	$mailstring = $mailstring.'Berufsfeld: '.$_POST['berufsfeld']."\n";
	$mailstring = $mailstring.'Zeitraum ab: '.$_POST['zeitraum_ab_m'].' / '.$_POST['zeitraum_ab_y']."\n";
	$mailstring = $mailstring.'Zeitraum: '.$_POST['zeitraum']."\n";
	$mailstring = $mailstring.'Beschreibung: '.$_POST['beschreibungen']."\n";
	$mailstring = $mailstring.'Qualifikation: '.$_POST['qualifikation']."\n";
	$mailstring = $mailstring.'sonstige Qualifikation: '.$_POST['sonst_qualifikation']."\n";
	$mailstring = $mailstring.'Arbeitsort: '.$_POST['arbeitsort']."\n";
	$mailstring = $mailstring.'Einsatzland: '.$_POST['einsatzland']."\n";
	$mailstring = $mailstring.'Kenntnisse: '.$_POST['kenntnisse']."\n";
	$mailstring = $mailstring.'vorherige Unternehmen: '.$_POST['vorh_unternehmen']."\n";
	$mailstring = $mailstring.'1. Sprache: '.$_POST['sprachkenntnisse1']."\n";
	$mailstring = $mailstring.'2. Sprache: '.$_POST['sprachkenntnisse2']."\n";
	$mailstring = $mailstring.'3. Sprache: '.$_POST['sprachkenntnisse3']."\n";
	$mailstring = $mailstring.'Datum Verfall: '.$datum_verfall."\n";
	$mailstring = $mailstring.'Host: '.$host."\n";
	$mailstring = $mailstring.'IP: '.$ip."\n";
	$mailstring = $mailstring.'Datum Eintrag: '.date('d-m-Y')."\n";
	$mailstring = $mailstring."\n\nDATENBANKSTRING:\n";
	$mailstring = $mailstring.$insertstring."\n";
	
	/* infomail verschicken */
	mail($infomail, $subject, $mailstring, "From: $infomail\nX-Mailer: praktika.de Mailscript PHP");
	
	/* ---------------------------------------------------------------------------------------------- */
	echo '<p>Ihr Gesuch wurde erfolgreich gespeichert!</p>'."\n";
	
	echo '<p class="control_panel"><button type="button" name="back" onclick="location.href = \'/karriere/gesuche/\'" value="zur&uuml;ck zur &Uuml;bersicht"><span><span><span>zur&uuml;ck zur &Uuml;bersicht</span></span></span></button></p>'."\n";
} else {
	$sprachen = mysql_db_query($database_db,'SELECT '.$_SESSION['s_sprache'].',id FROM sprachen WHERE inactive = \'false\' ORDER BY '.$_SESSION['s_sprache'],$praktdbslave);
	$anz_sprachen = mysql_num_rows($sprachen);

	$qualifikationen = mysql_db_query($database_db,'SELECT qualifikation,id FROM qualifikation ORDER BY qualifikation',$praktdbslave);
	$anz_qualifikationen = mysql_num_rows($qualifikationen);

	$berufsfelder = mysql_db_query($database_db,'SELECT * FROM berufsfelder WHERE '.$_SESSION['s_sprache'].' <> \'\' ORDER BY '.$_SESSION['s_sprache'],$praktdbslave);
	$anz_berufsfelder = mysql_num_rows($berufsfelder);
	
	$branchen = mysql_db_query($database_db,'SELECT * FROM branchen WHERE '.$_SESSION['s_sprache'].' <> \'\' ORDER BY '.$_SESSION['s_sprache'],$praktdbslave);
	$anz_branchen = mysql_num_rows($branchen);
	
	$landselect = mysql_db_query($database_db,'SELECT '.$_SESSION['s_sprache'].',id FROM land ORDER BY '.$_SESSION['s_sprache'],$praktdbslave);
	$anz_land = mysql_num_rows($landselect);
	$nutzerland = mysql_db_query($database_db,'SELECT land FROM nutzer WHERE id='.$_SESSION['s_nutzerid'],$praktdbslave);
	
	if (isset($_GET['id'])) {
		$nebenjobgesuch = mysql_db_query($database_db,'SELECT *,date_format(datum_verfall, \'%d\') AS tagv, date_format(datum_verfall, \'%m\') AS monatv, date_format(datum_verfall, \'%Y\') AS jahrv FROM nebenjobgesuch WHERE id = '.$_GET['id'].' AND nutzerid = '.$_SESSION['s_nutzerid'],$praktdbmaster);

		$_POST['taetigkeit'] = mysql_result($nebenjobgesuch,0,'taetigkeit');
		$_POST['sonst_qualifikation'] = mysql_result($nebenjobgesuch,0,'sonst_qualifikation');
		$_POST['zeitraum'] = mysql_result($nebenjobgesuch,0,'zeitraum');
		$_POST['arbeitsort'] = mysql_result($nebenjobgesuch,0,'arbeitsort');
		$_POST['einsatzland'] = mysql_result($nebenjobgesuch,0,'einsatzland');
		$_POST['qualifikation'] = mysql_result($nebenjobgesuch,0,'qualifikation');
		$_POST['zeitraum'] = mysql_result($nebenjobgesuch,0,'zeitraum');
		$_POST['beschreibungen'] = mysql_result($nebenjobgesuch,0,'beschreibung');
		$_POST['berufsfeld'] = mysql_result($nebenjobgesuch,0,'berufsfeld');
		$_POST['zeitraum_ab_m'] = mysql_result($nebenjobgesuch,0,'zeitraum_ab_m');
		$_POST['zeitraum_ab_y'] = mysql_result($nebenjobgesuch,0,'zeitraum_ab_y');
		$_POST['branche'] = explode(",",mysql_result($nebenjobgesuch,0,'branchen'));
		$_POST['kenntnisse'] = mysql_result($nebenjobgesuch,0,'kenntnisse');
		$_POST['vorh_unternehmen'] = mysql_result($nebenjobgesuch,0,'vorh_unternehmen');
		$_POST['sprachkenntnisse1'] = mysql_result($nebenjobgesuch,0,'sprachkenntnisse1');
		$_POST['sprachkenntnisse2'] = mysql_result($nebenjobgesuch,0,'sprachkenntnisse2');
		$_POST['sprachkenntnisse3'] = mysql_result($nebenjobgesuch,0,'sprachkenntnisse3');
		$_POST['verfall_tag'] = mysql_result($nebenjobgesuch,0,'tagv');
		$_POST['verfall_monat'] = mysql_result($nebenjobgesuch,0,'monatv');
		$_POST['verfall_jahr'] = mysql_result($nebenjobgesuch,0,'jahrv');
		$_POST['gesuch'] = $_GET['id'];
	}
	
	if (!isset($_POST['einsatzland'])) {
		$_POST['einsatzland'] = mysql_result($nutzerland,0,'land');
	}	
	
	if (isset($_POST['senden'])) {
		echo '<p class="error">Leider haben Sie die Felder nicht vollst&auml;ndig ausgef&uuml;llt.<br />Bitte korrigieren Sie Ihre Eingaben.</p>'."\n";
	}

	if (isset($_POST['senden']) && isset($insertstring)) {
		if (substr_count($insertstring,'@') > 0 || substr_count($insertstring,'www') > 0) {
			echo '<p class="error">Das Ver&ouml;ffentlichen von eMail- und Internetadressen ist aus Datenschutzgr&uuml;nden nicht erlaubt. Bitte entfernen Sie diese aus ihrem Text.</p>'."\n";
		}
	}

	echo '	<form action="/karriere/gesuche/nebenjob/" method="post">'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="auswahl">Art des Gesuches:</label>'."\n";
	echo '				<select id="auswahl" name="auswahl" onchange="Go(this.form.auswahl.options[this.form.auswahl.options.selectedIndex].value);">'."\n";
	echo '					<option value="/karriere/gesuche/praktikum/">Praktikum</option>'."\n";
	echo '					<option value="/karriere/gesuche/diplom/">Bachelor-/Masterarbeit</option>'."\n";
	echo '					<option value="/karriere/gesuche/berufseinstieg/">Berufseinstieg</option>'."\n";
	echo '					<option value="/karriere/gesuche/nebenjob/" selected="selected">Nebenjob</option>'."\n";
	echo '					<option value="/karriere/gesuche/ausbildung/">Ausbildung</option>'."\n";
	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<h4>Nebenjobbeschreibung</h4>'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="taetigkeit"';

	if (isset($_POST['senden']) && isset($_POST['taetigkeit']) && empty($_POST['taetigkeit'])) {
		echo ' style="color: #ff0000;"';
	}
	
	echo '>gew&uuml;nschte T&auml;tigkeit:</label>'."\n";
	echo '				<input id="taetigkeit" name="taetigkeit" value="'.(isset($_POST['taetigkeit']) ? $_POST['taetigkeit'] : '').'" maxlength="250" />'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="berufsfeld">Berufsfeld:</label>'."\n";
	echo '				<select id="berufsfeld" name="berufsfeld">'."\n";
	
	$i=0;
	while ($i < $anz_berufsfelder) {
		$html = htmlspecialchars(mysql_result($berufsfelder,$i,$_SESSION['s_sprache']));
		echo '					<option ';
		if (isset($_POST['berufsfeld'])) {
			if  (mysql_result($berufsfelder,$i,'id') == $_POST['berufsfeld']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.mysql_result($berufsfelder,$i,'id').'">'.$html.'</option>'."\n";
		$i++;
	};

	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="zeitraum_ab_m"';

	if (isset($_POST['senden']) && isset($_POST['zeitraum_ab_m']) && isset($_POST['zeitraum_ab_y']) &&(($_POST['zeitraum_ab_m'] < 1 || $_POST['zeitraum_ab_m'] > 12 ) || ($_POST['zeitraum_ab_y'] < date('Y')) || (empty($_POST['zeitraum_ab_m']) || empty($_POST['zeitraum_ab_y'])) || $_POST['zeitraum_ab_m'] > $_POST['zeitraum_ab_y']) && empty($zeitraum)) {
		echo ' style="color: #ff0000;"';
	}
	
	echo '>Zeitraum ab:</label>'."\n";
	echo '				<select id="zeitraum_ab_m" name="zeitraum_ab_m" class="month">'."\n";

	if (!isset($_POST['zeitraum_ab_m'])) {
		$_POST['zeitraum_ab_m'] = date('m');
	}
	
	$i=1;
	while ($i < 13) {
		echo '<option ';
		if (isset($_POST['zeitraum_ab_m'])) {
			if  ($i == $_POST['zeitraum_ab_m']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.$i.'">'.sprintf("%02.0f",$i).'</option>'."\n";
		$i++;
	}

	echo '				</select>&nbsp;/&nbsp;'."\n";
	echo '				<select name="zeitraum_ab_y" class="year">'."\n";

	$startyear = date('Y');
	$i = $startyear;
	while ($i < ($startyear + 4)) {
		echo '					<option ';
		if (isset($_POST['zeitraum_ab_y'])) {
			if  ($i == $_POST['zeitraum_ab_y']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.$i.'">'.sprintf("%01.0f",$i).'</option>'."\n";
		$i++;
	}

	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="zeitraum"';

	if (isset($_POST['senden']) && empty($_POST['von_tag']) && empty($_POST['zeitraum'])) {
		echo ' style="color: #ff0000;"';
	}
	echo '>Zeitraum Dauer:</label>'."\n";
	echo '				<input id="zeitraum" name="zeitraum" value="'.(isset($_POST['zeitraum']) ? $_POST['zeitraum'] : '').'" maxlength="100" />'."\n";
	echo '			</p>'."\n";

	if (isset($_POST['branche']) && !is_array($_POST['branche'])) {
		$_POST['branche'] = array();
	}
	$i=0;
	while ($i < $anz_branchen) {
		if ($i == 0) {
				echo '			<label for="branche'.$i.'">Branchenauswahl:</label>'."\n";
				echo '			<div class="col_2">'."\n";
		}
		
		$html = htmlspecialchars(mysql_result($branchen,$i,$_SESSION['s_sprache']));
		echo '				<p class="checkboxes">'."\n";
		echo '					<input type="checkbox" id="branche'.$i.'" name="branche[]" ';
		if (isset($_POST['branche'])) {
			if (in_array(mysql_result($branchen,$i,'id'),$_POST['branche'])) {
				echo 'checked="checked" ';
			}
		}
		echo 'value="'. mysql_result($branchen,$i,'id').'" />'."\n";
		echo '					<label for="branche'.$i.'">'.$html.'</label>'."\n";
		echo '				</p>'."\n";
		$i++;
	}

	echo '			</div>'."\n";
	echo '			<p style="clear: right; padding-top: 5px;">'."\n";
	echo '				<label for="beschreibungen"';

	if (isset($_POST['senden']) && empty($_POST['beschreibungen'])) {
		echo ' style="color: #ff0000;"';
	}

	echo '>Beschreibung Ihrer Nebenjobvorstellungen:</label>'."\n";
	echo '				<textarea id="beschreibungen" name="beschreibungen" cols="20" rows="6">'.htmlspecialchars((isset($_POST['beschreibungen']) ? $_POST['beschreibungen'] : '')).'</textarea>'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<h4>Qualifikation</h4>'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="qualifikation">Qualifikation:</label>'."\n";
	echo '				<select name="qualifikation" id="qualifikation">'."\n";

	$i=0;
	while ($i < $anz_qualifikationen) {
		$html = htmlspecialchars(mysql_result($qualifikationen,$i,'qualifikation'));
		echo '					<option ';
		if (isset($_POST['qualifikation'])) {
			if  (mysql_result($qualifikationen,$i,'id') == $_POST['qualifikation']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.mysql_result($qualifikationen,$i,'id').'">'.$html.'</option>'."\n";
		$i++;
	}
	
	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="sonst_qualifikation">sonstige Qualifikation:</label>'."\n";
	echo '				<input id="sonst_qualifikation" name="sonst_qualifikation" value="'.(isset($_POST['sonst_qualifikation']) ? $_POST['sonst_qualifikation'] : '').'" maxlength="200" />'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="kenntnisse">Besondere Kenntnisse:</label>'."\n";
	echo '				<textarea id="kenntnisse" name="kenntnisse" cols="20" rows="6">'.(isset($_POST['kenntnisse']) ? $_POST['kenntnisse'] : '').'</textarea>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="vorh_unternehmen">In welchem Unternehmen haben Sie bereits gearbeitet?:</label>'."\n";
	echo '				<textarea id="vorh_unternehmen" name="vorh_unternehmen" cols="20" rows="6">'.(isset($_POST['vorh_unternehmen']) ? $_POST['vorh_unternehmen'] : '').'</textarea>'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<h4>Regionale Einschr&auml;nkungen</h4>'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="arbeitsort"';

	if (isset($_POST['senden']) && isset($_POST['taetigkeit']) && empty($_POST['taetigkeit'])) {
		echo ' style="color: #ff0000;"';
	}
	
	echo '>gew&uuml;nschter Arbeitsort:</label>'."\n";
	echo '				<input id="arbeitsort" name="arbeitsort" value="'.(isset($_POST['arbeitsort']) ? $_POST['arbeitsort'] : '').'" maxlength="50" />'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="einsatzland">Einsatzland:</label>'."\n";
	echo '				<select id="einsatzland" name="einsatzland">'."\n";
	
	$i=0;
	while ($i < $anz_land) {
		$html = htmlspecialchars(mysql_result($landselect,$i,$_SESSION['s_sprache']));
		echo '					<option ';
		if (isset($_POST['einsatzland'])) {
			if  (mysql_result($landselect,$i,'id') == $_POST['einsatzland']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.mysql_result($landselect,$i,'id').'">'.$html.'</option>'."\n";
		$i++;
	};

	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<h4>Sprachen</h4>'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="sprachkenntnisse1">Sprachkenntnisse:</label>'."\n";
	echo '				<select name="sprachkenntnisse1" id="sprachkenntnisse1">'."\n";

	if (!isset($_POST['sprachkenntnisse1'])) {
		$_POST['sprachkenntnisse1'] = 2;
	}
	$i=0;
	while ($i < $anz_sprachen) {
		$html = htmlspecialchars(mysql_result($sprachen,$i,$_SESSION['s_sprache']));
		echo '					<option ';
		if (mysql_result($sprachen,$i,'id') == $_POST['sprachkenntnisse1']) {
			echo 'selected="selected" ';
		}
		echo 'value="'.mysql_result($sprachen,$i,'id').'">'.$html.'</option>'."\n";
		$i++;
	}
	
	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="sprachkenntnisse2">&nbsp;</label>'."\n";
	echo '				<select id="sprachkenntnisse2" name="sprachkenntnisse2">'."\n";

	$i=0;
	echo '					<option value="">--</option>'."\n";
	while ($i < $anz_sprachen) {
		$html = htmlspecialchars(mysql_result($sprachen,$i,$_SESSION['s_sprache']));
		echo '					<option ';
		if (isset($_POST['sprachkenntnisse2'])) {
			if (mysql_result($sprachen,$i,'id') == $_POST['sprachkenntnisse2']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.mysql_result($sprachen,$i,'id').'">'.$html.'</option>'."\n";
		$i++;
	}
	
	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="sprachkenntnisse3">&nbsp;</label>'."\n";
	echo '				<select id="sprachkenntnisse3" name="sprachkenntnisse3">'."\n";

	$i=0;
	echo '					<option value="">--</option>'."\n";
	while ($i < $anz_sprachen) {
		$html = htmlspecialchars(mysql_result($sprachen,$i,$_SESSION['s_sprache']));
		echo '					<option ';
		if (isset($_POST['sprachkenntnisse3'])) {
			if (mysql_result($sprachen,$i,'id') == $_POST['sprachkenntnisse3']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.mysql_result($sprachen,$i,'id').'">'.$html.'</option>'."\n";
		$i++;
	}
	
	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<h4>Verfall des Pratikumsgesuches</h4>'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="verfall_tag">Verfallsdatum:</label>'."\n";

	if (empty($_POST['verfall_jahr'])) {
		$verfall_jahr = date('Y');
		$verfall_jahr++;
	} else {
		$verfall_jahr = $_POST['verfall_jahr'];
	}
	
	echo '				<input id="verfall_tag" name="verfall_tag" maxlength="2" value="'.((isset($_POST['verfall_tag']) && !empty($_POST['verfall_tag'])) ? $_POST['verfall_tag'] : date('d')).'" class="day" />.<input name="verfall_monat" maxlength="2" value="'.((isset($_POST['verfall_monat']) && !empty($_POST['verfall_monat'])) ? $_POST['verfall_monat'] : date('m')).'" class="month" />.<input name="verfall_jahr" maxlength="4" value="'.$verfall_jahr.'" class="year" />'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<fieldset class="control_panel">'."\n";
	echo '			<p>'."\n";
	echo '				<input type="hidden" id="gesuch" name="gesuch" value="'.(isset($_POST['gesuch']) ? $_POST['gesuch'] : '').'" />'."\n";
	echo '				<button type="submit" id="senden" name="senden" value="Speichern"><span><span><span>speichern</span></span></span></button>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<button type="button" name="back" onclick="location.href = \'/karriere/gesuche/\'" value="zur Gesuche&uuml;bersicht"><span><span><span>zur Gesuche&uuml;bersicht</span></span></span></button>'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '	</form>'."\n";
}
bodyoff();
?>