<?
// Kann weg (by stefan)
require("/home/praktika/etc/config.inc.php");

if (!isset($_SESSION['s_loggedin']) || $_SESSION['s_loggedin'] == false) {
	header('Location: http://'.$_SERVER['HTTP_HOST'].'/login');
}

$_SESSION['restricted'] = RESTRICTED_CANDIDATE;
$_SESSION['current_user_group'] = USER_GROUP_CANDIDATES;
$_SESSION['current_page'] = PAGE_MY_PRAKTIKA;

pageheader(array('page_title' => 'Eintrag Bachelor-/Masterarbeitgesuch'));

if (isset($_POST['senden']) &&
	isset($_POST['titel']) &&
	isset($_POST['beschreibung']) &&
	isset($_POST['studienort']) &&
	isset($_POST['zeitraum']) &&
	isset($_POST['verfall_tag']) &&
	isset($_POST['verfall_monat']) &&
	isset($_POST['verfall_jahr']) &&
	!empty($_POST['titel']) &&
	!empty($_POST['beschreibung']) &&
	!empty($_POST['studienort']) &&
	!empty($_POST['zeitraum']) &&
	!empty($_POST['verfall_tag']) &&
	!empty($_POST['verfall_monat']) &&
	!empty($_POST['verfall_jahr'])) {
	
	/* datumsfelder zusammensetzen  */
	$datum_verfall = $_POST['verfall_jahr'].'-'.$_POST['verfall_monat'].'-'.$_POST['verfall_tag'];
	
	$branchenselect = mysql_db_query($database_db,'SELECT * FROM branchen WHERE '.$_SESSION['s_sprache'].' <> \'\' ORDER BY '.$_SESSION['s_sprache'],$praktdbslave);
	while ($row = mysql_fetch_array($branchenselect, MYSQL_ASSOC)) {
	   $branchen[$row['id']] = $row[$_SESSION['s_sprache']];
	}
	
	if (isset($_POST['branche']) && is_array($_POST['branche'])) {
		$branchetext = array();
		foreach ($_POST['branche'] as $brancheitem) {
			$branchetext[] = $branchen[$brancheitem];
		}
	} else {
		$_POST['branche'] = array();
		$branchetext = array();
	}
	
	/* einfuegestring zusammensetzen */
	$insertstring = 'REPLACE INTO diplomgesuch (
						'.((isset($_POST['gesuch']) && !empty($_POST['gesuch'])) ? 'id,' : '').'
						inactive,
						nutzerid,
						branchen,
						branchentext,
						berufsfeld,
						titel,
						beschreibung,
						einsatzland,
						schlagwort,
						zeitraum_ab_m,
						zeitraum_ab_y,
						zeitraum,
						studienort,
						datum_eintrag,
						datum_verfall,
						modify
					) VALUES (
						'.((isset($_POST['gesuch']) && !empty($_POST['gesuch'])) ? intval($_POST['gesuch']).',' : '').'
						\'false\',
						'.intval($_SESSION['s_nutzerid']).',
						\''.implode(',',$_POST['branche']).'\',
						\''.implode(' ',$branchetext).'\',
						'.intval($_POST['berufsfeld']).',
						\''.mysql_real_escape_string($_POST['titel']).'\',
						\''.mysql_real_escape_string($_POST['beschreibung']).'\',
						'.intval($_POST['einsatzland']).',
						\''.mysql_real_escape_string($_POST['schlagwort']).'\',
						'.intval($_POST['zeitraum_ab_m']).',
						'.intval($_POST['zeitraum_ab_y']).',
						\''.mysql_real_escape_string($_POST['zeitraum']).'\',
						\''.mysql_real_escape_string($_POST['studienort']).'\',
						NOW(),
						\''.$datum_verfall.'\',
						NOW()
					)';
	//echo $insertstring;
	/* datensatz einfuegen */
	mysql_db_query($database_db,$insertstring,$praktdbmaster);
	
	/* id bestimmen */
	$insert_id = mysql_insert_id($praktdbmaster);
	
	/* Logfile eintragen */
	$fp = fopen($logfile, 'a');
	fputs($fp, $insertstring);
	fputs($fp, "\n");
	fclose($fp);

	/* infomail zusammenbauen */
	$subject = 'praktika.de Neues Diplomthemengesuch - ID: '.$insert_id;
	$mailstring ='DIPLOMTHEMA - EINTRAG'."\n\n";
	$mailstring = $mailstring.'ID: '.$insert_id."\n\n";
	$mailstring = $mailstring.'NUTZERID: '.$_SESSION['s_nutzerid']."\n\n";
	$mailstring = $mailstring.'Titel: '.$_POST['titel']."\n";
	$mailstring = $mailstring.'Beschreibung: '.$_POST['beschreibung']."\n";
	$mailstring = $mailstring.'Einsatzland: '.$_POST['einsatzland']."\n";
	$mailstring = $mailstring.'Schlagwort: '.$_POST['schlagwort']."\n";
	$mailstring = $mailstring.'Zeitraum: '.$_POST['zeitraum']."\n";
	$mailstring = $mailstring.'Studienort: '.$_POST['studienort']."\n";
	$mailstring = $mailstring."\n\n".'DATENBANKSTRING: '."\n";
	$mailstring = $mailstring.$insertstring."\n";
	
	/* infomail verschicken */
	mail($infomail, $subject, $mailstring, "From: $infomail\nX-Mailer: praktika.de Mailscript PHP");
	
	/* ---------------------------------------------------------------------------------------------- */
	echo '<p>Ihr Gesuch wurde erfolgreich gespeichert!</p>'."\n";
	
	echo '<p class="control_panel"><button type="button" name="back" onclick="location.href = \'/karriere/gesuche/\'" value="zur&uuml;ck zur &Uuml;bersicht"><span><span><span>zur&uuml;ck zur &Uuml;bersicht</span></span></span></button></p>'."\n";
} else {
	$qualifikationen = mysql_db_query($database_db,'SELECT qualifikation,id FROM qualifikation ORDER BY qualifikation',$praktdbslave);
	$anz_qualifikationen = mysql_num_rows($qualifikationen);

	$berufsfelder = mysql_db_query($database_db,'SELECT * FROM berufsfelder WHERE '.$_SESSION['s_sprache'].' <> \'\' ORDER BY '.$_SESSION['s_sprache'],$praktdbslave);
	$anz_berufsfelder = mysql_num_rows($berufsfelder);
	
	$branchen = mysql_db_query($database_db,'SELECT * FROM branchen WHERE '.$_SESSION['s_sprache'].' <> \'\' ORDER BY '.$_SESSION['s_sprache'],$praktdbslave);
	$anz_branchen = mysql_num_rows($branchen);
	
	$landselect = mysql_db_query($database_db,'SELECT '.$_SESSION['s_sprache'].',id FROM land ORDER BY '.$_SESSION['s_sprache'],$praktdbslave);
	$anz_land = mysql_num_rows($landselect);
	$nutzerland = mysql_db_query($database_db,'SELECT land FROM nutzer WHERE id='.$_SESSION['s_nutzerid'],$praktdbslave);

	if (isset($_GET['id'])) {
		$diplomgesuch = mysql_db_query($database_db,'SELECT *,date_format(datum_verfall, \'%d\') AS tagv, date_format(datum_verfall, \'%m\') AS monatv, date_format(datum_verfall, \'%Y\') AS jahrv FROM diplomgesuch WHERE id = '.$_GET['id'].' AND nutzerid = '.$_SESSION['s_nutzerid'],$praktdbmaster);

		$_POST['studienort'] = mysql_result($diplomgesuch,0,'studienort');
		$_POST['zeitraum'] = mysql_result($diplomgesuch,0,'zeitraum');
		$_POST['schlagwort'] = mysql_result($diplomgesuch,0,'schlagwort');
		$_POST['einsatzland'] = mysql_result($diplomgesuch,0,'einsatzland');
		$_POST['titel'] = mysql_result($diplomgesuch,0,'titel');
		$_POST['studiengang'] = mysql_result($diplomgesuch,0,'studiengang');
		$_POST['beschreibung'] = mysql_result($diplomgesuch,0,'beschreibung');
		$_POST['berufsfeld'] = mysql_result($diplomgesuch,0,'berufsfeld');
		$_POST['zeitraum_ab_m'] = mysql_result($diplomgesuch,0,'zeitraum_ab_m');
		$_POST['zeitraum_ab_y'] = mysql_result($diplomgesuch,0,'zeitraum_ab_y');
		$_POST['branche'] = explode(",",mysql_result($diplomgesuch,0,'branchen'));
		$_POST['verfall_tag'] = mysql_result($diplomgesuch,0,'tagv');
		$_POST['verfall_monat'] = mysql_result($diplomgesuch,0,'monatv');
		$_POST['verfall_jahr'] = mysql_result($diplomgesuch,0,'jahrv');
		$_POST['gesuch'] = $_GET['id'];
	}	

	if (!isset($_POST['einsatzland'])) {
		$_POST['einsatzland'] = mysql_result($nutzerland,0,'land');
	}
	
	if (isset($_POST['senden'])) {
		echo '<p class="error">Leider haben Sie die Felder nicht vollst&auml;ndig ausgef&uuml;llt.<br />Bitte korrigieren Sie Ihre Eingaben.</p>'."\n";
	}

	if (isset($_POST['senden']) && isset($insertstring)) {
		if (substr_count($insertstring,'@') > 0 || substr_count($insertstring,'www') > 0) {
			echo '<p class="error">Das Ver&ouml;ffentlichen von eMail- und Internetadressen ist aus Datenschutzgr&uuml;nden nicht erlaubt. Bitte entfernen Sie diese aus ihrem Text.</p>'."\n";
		}
	}

	echo '	<form action="/karriere/gesuche/diplom/" method="post">'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="auswahl">Art des Gesuches:</label>'."\n";
	echo '				<select id="auswahl" name="auswahl" onchange="Go(this.form.auswahl.options[this.form.auswahl.options.selectedIndex].value);">'."\n";
	echo '					<option value="/karriere/gesuche/praktikum/">Praktikum</option>'."\n";
	echo '					<option value="/karriere/gesuche/diplom/" selected="selected">Bachelor-/Masterarbeit</option>'."\n";
	echo '					<option value="/karriere/gesuche/berufseinstieg/">Berufseinstieg</option>'."\n";
	echo '					<option value="/karriere/gesuche/nebenjob/">Nebenjob</option>'."\n";
	echo '					<option value="/karriere/gesuche/ausbildung/">Ausbildung</option>'."\n";
	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<h4>Beschreibung des Bachelor-/Masterarbeitsthema</h4>'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="titel"';

	if (isset($_POST['senden']) && isset($_POST['titel']) && empty($_POST['titel'])) {
		echo ' style="color: #ff0000;"';
	}
	
	echo '>Titel der Bachelor-/Masterarbeit:</label>'."\n";
	echo '				<textarea id="titel" name="titel" cols="20" rows="2">'.(isset($_POST['titel']) ? $_POST['titel'] : '').'</textarea>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="beschreibung"';

	if (isset($_POST['senden']) && isset($_POST['beschreibung']) && empty($_POST['beschreibung'])) {
		echo ' style="color: #ff0000;"';
	}
	
	echo '>Beschreibung der Bachelor-/Masterarbeit:</label>'."\n";
	echo '				<textarea id="beschreibung" name="beschreibung" cols="20" rows="10">'.(isset($_POST['beschreibung']) ? $_POST['beschreibung'] : '').'</textarea>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="berufsfeld">Berufsfeld:</label>'."\n";
	echo '				<select id="berufsfeld" name="berufsfeld">'."\n";
	
	$i=0;
	while ($i < $anz_berufsfelder) {
		$html = htmlspecialchars(mysql_result($berufsfelder,$i,$_SESSION['s_sprache']));
		echo '					<option ';
		if (isset($_POST['berufsfeld'])) {
			if  (mysql_result($berufsfelder,$i,'id') == $_POST['berufsfeld']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.mysql_result($berufsfelder,$i,'id').'">'.$html.'</option>'."\n";
		$i++;
	};

	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="einsatzland">Einsatzland:</label>'."\n";
	echo '				<select id="einsatzland" name="einsatzland">'."\n";
	
	$i=0;
	while ($i < $anz_land) {
		$html = htmlspecialchars(mysql_result($landselect,$i,$_SESSION['s_sprache']));
		echo '					<option ';
		if (isset($_POST['einsatzland'])) {
			if  (mysql_result($landselect,$i,'id') == $_POST['einsatzland']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.mysql_result($landselect,$i,'id').'">'.$html.'</option>'."\n";
		$i++;
	};

	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="studienort"';

	if (isset($_POST['senden']) && isset($_POST['studienort']) && empty($_POST['studienort'])) {
		echo ' style="color: #ff0000;"';
	}
	
	echo '>Ort der Bachelor-/Masterarbeit:</label>'."\n";
	echo '				<input id="studienort" name="studienort" maxlength="50"  value="'.(isset($_POST['studienort']) ? $_POST['studienort'] : '').'" />'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="schlagwort">Schlagw&ouml;rter:</label>'."\n";
	echo '				<input id="schlagwort" name="schlagwort" maxlength="250"  value="'.(isset($_POST['schlagwort']) ? $_POST['schlagwort'] : '').'" />'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="zeitraum_ab_m"';

	if (isset($_POST['senden']) && isset($_POST['zeitraum_ab_m']) && isset($_POST['zeitraum_ab_y']) &&(($_POST['zeitraum_ab_m'] < 1 || $_POST['zeitraum_ab_m'] > 12 ) || ($_POST['zeitraum_ab_y'] < date('Y')) || (empty($_POST['zeitraum_ab_m']) || empty($_POST['zeitraum_ab_y'])) || $_POST['zeitraum_ab_m'] > $_POST['zeitraum_ab_y']) && empty($zeitraum)) {
		echo ' style="color: #ff0000;"';
	}
	
	echo '>Zeitraum ab:</label>'."\n";
	echo '				<select id="zeitraum_ab_m" name="zeitraum_ab_m" class="month">'."\n";

	if (!isset($_POST['zeitraum_ab_m'])) {
		$_POST['zeitraum_ab_m'] = date('m');
	}
	
	$i=1;
	while ($i < 13) {
		echo '<option ';
		if (isset($_POST['zeitraum_ab_m'])) {
			if  ($i == $_POST['zeitraum_ab_m']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.$i.'">'.sprintf("%02.0f",$i).'</option>'."\n";
		$i++;
	}

	echo '				</select>&nbsp;/&nbsp;'."\n";
	echo '				<select name="zeitraum_ab_y" class="year">'."\n";

	$startyear = date('Y');
	$i = $startyear;
	while ($i < ($startyear + 4)) {
		echo '					<option ';
		if (isset($_POST['zeitraum_ab_y'])) {
			if  ($i == $_POST['zeitraum_ab_y']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.$i.'">'.sprintf("%01.0f",$i).'</option>'."\n";
		$i++;
	}

	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="zeitraum"';

	if (isset($_POST['senden']) && empty($_POST['von_tag']) && empty($_POST['zeitraum'])) {
		echo ' style="color: #ff0000;"';
	}
	echo '>Zeitraum Dauer:</label>'."\n";
	echo '				<input id="zeitraum" name="zeitraum" value="'.(isset($_POST['zeitraum']) ? $_POST['zeitraum'] : '').'" maxlength="100" />'."\n";
	echo '			</p>'."\n";

	if (isset($_POST['branche']) && !is_array($_POST['branche'])) {
		$_POST['branche'] = array();
	}
	$i=0;
	while ($i < $anz_branchen) {
		if ($i == 0) {
				echo '			<label for="branche'.$i.'">Branchenauswahl:</label>'."\n";
				echo '			<div class="col_2">'."\n";
		}
		
		$html = htmlspecialchars(mysql_result($branchen,$i,$_SESSION['s_sprache']));
		echo '				<p class="checkboxes">'."\n";
		echo '					<input type="checkbox" id="branche'.$i.'" name="branche[]" ';
		if (isset($_POST['branche'])) {
			if (in_array(mysql_result($branchen,$i,'id'),$_POST['branche'])) {
				echo 'checked="checked" ';
			}
		}
		echo 'value="'. mysql_result($branchen,$i,'id').'" />'."\n";
		echo '					<label for="branche'.$i.'">'.$html.'</label>'."\n";
		echo '				</p>'."\n";
		$i++;
	}

	echo '			</div>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<h4>Verfall des Bachelor-/Masterarbeitsgesuches</h4>'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="verfall_tag">Verfallsdatum:</label>'."\n";

	if (empty($_POST['verfall_jahr'])) {
		$verfall_jahr = date('Y');
		$verfall_jahr++;
	} else {
		$verfall_jahr = $_POST['verfall_jahr'];
	}
	
	echo '				<input id="verfall_tag" name="verfall_tag" maxlength="2" value="'.((isset($_POST['verfall_tag']) && !empty($_POST['verfall_tag'])) ? $_POST['verfall_tag'] : date('d')).'" class="day" />.<input name="verfall_monat" maxlength="2" value="'.((isset($_POST['verfall_monat']) && !empty($_POST['verfall_monat'])) ? $_POST['verfall_monat'] : date('m')).'" class="month" />.<input name="verfall_jahr" maxlength="4" value="'.$verfall_jahr.'" class="year" />'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<fieldset class="control_panel">'."\n";
	echo '			<p>'."\n";
	echo '				<input type="hidden" id="gesuch" name="gesuch" value="'.(isset($_POST['gesuch']) ? $_POST['gesuch'] : '').'" />'."\n";
	echo '				<button type="submit" id="senden" name="senden" value="Speichern"><span><span><span>speichern</span></span></span></button>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<button type="button" name="back" onclick="location.href = \'/karriere/gesuche/\'" value="zur Gesuche&uuml;bersicht"><span><span><span>zur Gesuche&uuml;bersicht</span></span></span></button>'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '	</form>'."\n";
}
bodyoff();
?>