<?
// Kann weg (by stefan)
require("/home/praktika/etc/config.inc.php");

if (!isset($_SESSION['s_loggedin']) || $_SESSION['s_loggedin'] == false) {
	header('Location: http://'.$_SERVER['HTTP_HOST'].'/login');
}

$_SESSION['restricted'] = RESTRICTED_CANDIDATE;
$_SESSION['current_user_group'] = USER_GROUP_CANDIDATES;
$_SESSION['current_page'] = PAGE_MY_PRAKTIKA;

pageheader(array('page_title' => 'Eintrag eines neuen Praktikumsgesuchs'));

if (isset($_POST['senden']) &&
	isset($_POST['beschreibungen']) &&
	isset($_POST['taetigkeit']) &&
	isset($_POST['verfall_tag']) &&
	isset($_POST['verfall_monat']) &&
	isset($_POST['verfall_jahr']) &&
	!empty($_POST['beschreibungen']) &&
	!empty($_POST['taetigkeit']) &&
	!empty($_POST['verfall_tag']) &&
	!empty($_POST['verfall_monat']) &&
	!empty($_POST['verfall_jahr'])) {

	/* datumsfelder zusammensetzen  */
	$datum_verfall = $_POST['verfall_jahr'].'-'.$_POST['verfall_monat'].'-'.$_POST['verfall_tag'];
	
	$branchenselect = mysql_db_query($database_db,'SELECT * FROM branchen WHERE '.$_SESSION['s_sprache'].' <> \'\' ORDER BY '.$_SESSION['s_sprache'],$praktdbslave);
	while ($row = mysql_fetch_array($branchenselect, MYSQL_ASSOC)) {
	   $branchen[$row['id']] = $row[$_SESSION['s_sprache']];
	}
	
	if (isset($_POST['branche']) && is_array($_POST['branche'])) {
		$branchetext = array();
		foreach ($_POST['branche'] as $brancheitem) {
			$branchetext[] = $branchen[$brancheitem];
		}
	} else {
		$_POST['branche'] = array();
		$branchetext = array();
	}
	
	/* einfuegestring zusammensetzen */
	$insertstring = 'REPLACE INTO praktikanten (
						'.((isset($_POST['gesuch']) && !empty($_POST['gesuch'])) ? 'id,' : '').'
						inactive,
						nutzerid,
						taetigkeit,
						berufsfeld,
						praktikumsart,
						zeitraum_ab_m,
						zeitraum_ab_y,
						zeitraum,
						beschreibung,
						qualifikation,
						sonst_qualifikation,
						studienort,
						branchen,
						branchentext,
						umschulung,
						vorh_praktika,
						sprachkenntnisse1,
						sprachkenntnisse2,
						sprachkenntnisse3,
						host,
						ip,
						datum_eintrag,
						datum_verfall,
						modify
					) VALUES (
						'.((isset($_POST['gesuch']) && !empty($_POST['gesuch'])) ? intval($_POST['gesuch']).',' : '').'
						\'false\',
						'.intval($_SESSION['s_nutzerid']).',
						\''.mysql_real_escape_string($_POST['taetigkeit']).'\',
						'.intval($_POST['berufsfeld']).',
						'.intval($_POST['praktikumsart']).',
						'.intval($_POST['zeitraum_ab_m']).',
						'.intval($_POST['zeitraum_ab_y']).',
						\''.mysql_real_escape_string($_POST['zeitraum']).'\',
						\''.mysql_real_escape_string($_POST['beschreibungen']).'\',
						'.intval($_POST['qualifikation']).',
						\''.mysql_real_escape_string($_POST['sonst_qualifikation']).'\',
						\''.mysql_real_escape_string($_POST['studienort']).'\',
						\''.implode(',',$_POST['branche']).'\',
						\''.implode(' ',$branchetext).'\',
						\''.mysql_real_escape_string($_POST['umschulung']).'\',
						\''.mysql_real_escape_string($_POST['vorh_praktika']).'\',
						'.intval($_POST['sprachkenntnisse1']).',
						'.((isset($_POST['sprachkenntnisse2']) && !empty($_POST['sprachkenntnisse2'])) ? intval($_POST['sprachkenntnisse2']) : 'NULL').',
						'.((isset($_POST['sprachkenntnisse3']) && !empty($_POST['sprachkenntnisse3'])) ? intval($_POST['sprachkenntnisse2']) : 'NULL').',
						\''.$host.'\',
						\''.$ip.'\',
						NOW(),
						\''.$datum_verfall.'\',
						NOW()
					)';
	//echo $insertstring;
	/* datensatz einfuegen */
	mysql_db_query($database_db,$insertstring,$praktdbmaster);
	
	/* id bestimmen */
	$insert_id = mysql_insert_id($praktdbmaster);
	
	/* Logfile eintragen */
	$fp = fopen($logfile, 'a');
	fputs($fp, $insertstring);
	fputs($fp, "\n");
	fclose($fp);
	
	/*$emailobj = new emailtemplate(33);
	$emailobj->replace('{insert_id}',$insert_id);
	$emailobj->replace('{taetigkeit}',$_POST['taetigkeit']);
	$emailobj->replace('{berufsfeld}',$_POST['berufsfeld']);
	$emailobj->replace('{praktikumsart}',$_POST['praktikumsart']);
	$emailobj->replace('{zeitraum_von}',$_POST['zeitraum_ab_m']);
	$emailobj->replace('{zeitraum_bis}',$_POST['zeitraum_ab_y']);
	$emailobj->replace('{zeitraum}',$_POST['zeitraum']);
	$emailobj->replace('{beschreibung}',$_POST['beschreibungen']);
	$emailobj->replace('{qualifikation}',$_POST['qualifikation']);
	$emailobj->replace('{sonst_qualifikation}', $_POST['sonst_qualifikation']);
	$emailobj->replace('{studienort}',$_POST['studienort']);
	$emailobj->replace('{umschulung}',$_POST['umschulung']);
	$emailobj->replace('{vorh_praktika}',$_POST['vorh_praktika']);
	$emailobj->replace('{sprachkenntnisse1}',$_POST['sprachkenntnisse1']);
	$emailobj->replace('{sprachkenntnisse2}',$_POST['sprachkenntnisse2']);
	$emailobj->replace('{sprachkenntnisse3}',$_POST['sprachkenntnisse3']);
	$emailobj->replace('{datum_verfall}',$datum_verfall);
	$emailobj->replace('{host}',$host);
	$emailobj->replace('{ip}',$ip);
	$emailobj->replace('{datum_eintrag}',date('d-m-Y'));
	$emailobj->replace('{insertstring}',$insertstring);
	$emailobj->send_email();
	unset($emailobj);*/
	/* infomail zusammenbauen */
	$subject = 'praktika.de BEWERBER-EINTRAG BERUFSGESUCH: ID: '.$insert_id;
	$mailstring = 'BEWERBER BERUFSGESUCH - EINTRAG'."\n\n";
	$mailstring = $mailstring.'NUTZER-ID: '.$_SESSION['s_nutzerid']."\n\n";
	$mailstring = $mailstring.'ID: '.$insert_id."\n\n";
	$mailstring = $mailstring.'T&auml;tigkeit: '.$_POST['taetigkeit']."\n";
	$mailstring = $mailstring.'Berufsfeld: '.$_POST['berufsfeld']."\n";
	$mailstring = $mailstring.'Praktikumsart: '.$_POST['praktikumsart']."\n";
	$mailstring = $mailstring.'ab wann: '.$_POST['zeitraum_ab_m'].' '.$_POST['zeitraum_ab_y']."\n";
	$mailstring = $mailstring.'Zeitraum: '.$_POST['zeitraum']."\n";
	$mailstring = $mailstring.'Beschreibung: '.$_POST['beschreibungen']."\n";
	$mailstring = $mailstring.'Qualifikation: '.$_POST['qualifikation']."\n";
	$mailstring = $mailstring.'sonstige Qualifikationen: '.$_POST['sonst_qualifikation']."\n";
	$mailstring = $mailstring.'Studienort: '.$_POST['studienort']."\n";
	$mailstring = $mailstring.'Kenntnisse: '.$_POST['umschulung']."\n";
	$mailstring = $mailstring.'vorherige Praktika: '.$_POST['vorh_praktika']."\n";
	$mailstring = $mailstring.'1. Sprache: '.$_POST['sprachkenntnisse1']."\n";
	$mailstring = $mailstring.'2. Sprache: '.$_POST['sprachkenntnisse2']."\n";
	$mailstring = $mailstring.'3. Sprache: '.$_POST['sprachkenntnisse3']."\n";
	$mailstring = $mailstring.'Verfallsdatum: '.$datum_verfall."\n";
	$mailstring = $mailstring.'Host: '.$host."\n";
	$mailstring = $mailstring.'IP: '.$ip."\n";
	$mailstring = $mailstring.'Datum Eintrag: '.date('d-m-Y')."\n";
	$mailstring = $mailstring."\n\n".'DATENBANKSTRING:'."\n";
	$mailstring = $mailstring.$insertstring."\n";
	
	/* infomail verschicken */
	mail($infomail, $subject, $mailstring, "From: $infomail\nX-Mailer: praktika.de Mailscript PHP");	
	
	/* ---------------------------------------------------------------------------------------------- */
	
	/* Praktikumsbeschreibung */
	echo '<p>Ihr Gesuch wurde erfolgreich gespeichert!</p>'."\n";
	echo '<p><b>Ihre weiteren M&ouml;glichkeiten</b></p>'."\n";
	
	echo '<ol>'."\n";
	echo '	<li>Mit unserem Bewerbungspackage in Deutsch, Englisch, Spanisch, Franz&ouml;sisch, T&uuml;rkisch und Russisch erstellen Sie m&uuml;helos Ihre professionelle Bewerbungsmappe in verschiedenen Sprachen. <a href="/home/toppraktika/praktika-set/index.phtml">Mehr dazu hier!</a></li>'."\n";
	echo '	<li>Bis zu 2.000 EURO w&auml;hrend eines Praktikums verdienen? Mit nur 15 EURO liefern wir die notwendigen Informationen! <a href="/home/praktikanten/geldsuche.phtml">Mehr dazu hier!</a></li>'."\n";
	echo '	<li>Ihr pers&ouml;nliches Karriereprofil mit Lebenslauf. Sie k&ouml;nnen sich bei allen Unternehmen Ihres Merkzettels in Sekunden bewerben. <a href="/lebenslauf/">Mehr dazu hier!</a></li>'."\n";
	echo '	<li><a href="/karriere/gesuche/vorschau/'.$insert_id.'/">Vorschau</a> dieses Gesuches</li>'."\n";
	echo '	<li><a href="/karriere/gesuche/praktikum/'.$insert_id.'/">&Auml;nderung</a> dieses Gesuches</li>'."\n";
	echo '</ol>'."\n";
	
	echo '<p class="control_panel"><button type="button" name="back" onclick="location.href = \'/karriere/gesuche/\'" value="zur&uuml;ck zur &Uuml;bersicht"><span><span><span>zur&uuml;ck zur &Uuml;bersicht</span></span></span></button></p>'."\n";
} else {
	$sprachen = mysql_db_query($database_db,'SELECT '.$_SESSION['s_sprache'].',id FROM sprachen WHERE inactive = \'false\' ORDER BY '.$_SESSION['s_sprache'],$praktdbslave);
	$anz_sprachen = mysql_num_rows($sprachen);

	$qualifikationen = mysql_db_query($database_db,'SELECT qualifikation,id FROM qualifikation ORDER BY qualifikation',$praktdbslave);
	$anz_qualifikationen = mysql_num_rows($qualifikationen);

	$praktikumsarten = mysql_db_query($database_db,'SELECT * FROM praktikumsart ORDER BY art',$praktdbslave);
	$anz_praktikumsarten = mysql_num_rows($praktikumsarten);
	
	$berufsfelder = mysql_db_query($database_db,'SELECT * FROM berufsfelder WHERE '.$_SESSION['s_sprache'].' <> \'\' ORDER BY '.$_SESSION['s_sprache'],$praktdbslave);
	$anz_berufsfelder = mysql_num_rows($berufsfelder);
	
	$branchen = mysql_db_query($database_db,'SELECT * FROM branchen WHERE '.$_SESSION['s_sprache'].' <> \'\' ORDER BY '.$_SESSION['s_sprache'],$praktdbslave);
	$anz_branchen = mysql_num_rows($branchen);

	if (isset($_GET['id'])) {
		$prakgesuch = mysql_db_query($database_db,'SELECT *,date_format(datum_verfall, \'%d\') AS tagv, date_format(datum_verfall, \'%m\') AS monatv, date_format(datum_verfall, \'%Y\') AS jahrv FROM praktikanten WHERE id = '.$_GET['id'].' AND nutzerid = '.$_SESSION['s_nutzerid'],$praktdbmaster);
		
		$_POST['praktikumsart'] = mysql_result($prakgesuch,0,"praktikumsart");
		$_POST['taetigkeit'] = mysql_result($prakgesuch,0,"taetigkeit");
		$_POST['qualifikation'] = mysql_result($prakgesuch,0,"qualifikation");
		$_POST['sonst_qualifikation'] = mysql_result($prakgesuch,0,"sonst_qualifikation");
		$_POST['sprachkenntnisse1'] = mysql_result($prakgesuch,0,"sprachkenntnisse1");
		$_POST['sprachkenntnisse2'] = mysql_result($prakgesuch,0,"sprachkenntnisse2");
		$_POST['sprachkenntnisse3'] = mysql_result($prakgesuch,0,"sprachkenntnisse3");
		$_POST['studienort'] = mysql_result($prakgesuch,0,"studienort");
		$_POST['umschulung'] = mysql_result($prakgesuch,0,"umschulung");
		$_POST['vorh_praktika'] = mysql_result($prakgesuch,0,"vorh_praktika");
		$_POST['beschreibungen'] = mysql_result($prakgesuch,0,"beschreibung");
		$_POST['berufsfeld'] = mysql_result($prakgesuch,0,"berufsfeld");
		$_POST['zeitraum_ab_m'] = mysql_result($prakgesuch,0,"zeitraum_ab_m");
		$_POST['zeitraum_ab_y'] = mysql_result($prakgesuch,0,"zeitraum_ab_y");
		$_POST['zeitraum'] = mysql_result($prakgesuch,0,"zeitraum");
		$_POST['branche'] = explode(",",mysql_result($prakgesuch,0,"branchen"));
		$_POST['verfall_tag'] = mysql_result($prakgesuch,0,"tagv");
		$_POST['verfall_monat'] = mysql_result($prakgesuch,0,"monatv");
		$_POST['verfall_jahr'] = mysql_result($prakgesuch,0,"jahrv");
		$_POST['gesuch'] = $_GET['id'];
	}	
	
	if (isset($_POST['senden'])) {
		echo '<p class="error">Leider haben Sie die Felder nicht vollst&auml;ndig ausgef&uuml;llt.<br />Bitte korrigieren Sie Ihre Eingaben.</p>'."\n";
	}

	if (isset($_POST['senden']) && isset($insertstring)) {
		if (substr_count($insertstring,'@') > 0 || substr_count($insertstring,'www') > 0) {
			echo '<p class="error">Das Ver&ouml;ffentlichen von eMail- und Internetadressen ist aus Datenschutzgr&uuml;nden nicht erlaubt. Bitte entfernen Sie diese aus ihrem Text.</p>'."\n";
		}
	}

	echo '	<form action="/karriere/gesuche/praktikum/" method="post">'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="auswahl">Art des Gesuches:</label>'."\n";
	echo '				<select id="auswahl" name="auswahl" onchange="Go(this.form.auswahl.options[this.form.auswahl.options.selectedIndex].value);">'."\n";
	echo '					<option value="/karriere/gesuche/praktikum/" selected="selected">Praktikum</option>'."\n";
	echo '					<option value="/karriere/gesuche/diplom/">Bachelor-/Masterarbeit</option>'."\n";
	echo '					<option value="/karriere/gesuche/berufseinstieg/">Berufseinstieg</option>'."\n";
	echo '					<option value="/karriere/gesuche/nebenjob/">Nebenjob</option>'."\n";
	echo '					<option value="/karriere/gesuche/ausbildung/">Ausbildung</option>'."\n";
	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<h4>Praktikumsbeschreibung</h4>'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="taetigkeit"';

	if (isset($_POST['senden']) && isset($_POST['taetigkeit']) && empty($_POST['taetigkeit'])) {
		echo ' style="color: #ff0000;"';
	}
	
	echo '>gew&uuml;nschte T&auml;tigkeit:</label>'."\n";
	echo '				<input id="taetigkeit" name="taetigkeit" value="'.(isset($_POST['taetigkeit']) ? $_POST['taetigkeit'] : '').'" maxlength="250" />'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="berufsfeld">Berufsfeld:</label>'."\n";
	echo '				<select id="berufsfeld" name="berufsfeld">'."\n";
	
	$i=0;
	while ($i < $anz_berufsfelder) {
		$html = htmlspecialchars(mysql_result($berufsfelder,$i,$_SESSION['s_sprache']));
		echo '					<option ';
		if (isset($_POST['berufsfeld'])) {
			if  (mysql_result($berufsfelder,$i,'id') == $_POST['berufsfeld']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.mysql_result($berufsfelder,$i,'id').'">'.$html.'</option>'."\n";
		$i++;
	};

	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="praktikumsart">Praktikumsart:</label>'."\n";
	echo '				<select id="praktikumsart" name="praktikumsart">'."\n";

	$i=0;
	while ($i < $anz_praktikumsarten) {
		$html = htmlspecialchars(mysql_result($praktikumsarten,$i,'art'));
		echo '					<option ';
		if (isset($_POST['praktikumsart'])) {
			if  (mysql_result($praktikumsarten,$i,'id') == $_POST['praktikumsart']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.mysql_result($praktikumsarten,$i,'id').'">'.$html.'</option>'."\n";
		$i++;
	};
	
	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="zeitraum_ab_m"';

	if (isset($_POST['senden']) && isset($_POST['zeitraum_ab_m']) && isset($_POST['zeitraum_ab_y']) &&(($_POST['zeitraum_ab_m'] < 1 || $_POST['zeitraum_ab_m'] > 12 ) || ($_POST['zeitraum_ab_y'] < date('Y')) || (empty($_POST['zeitraum_ab_m']) || empty($_POST['zeitraum_ab_y'])) || $_POST['zeitraum_ab_m'] > $_POST['zeitraum_ab_y']) && empty($zeitraum)) {
		echo ' style="color: #ff0000;"';
	}
	
	echo '>Zeitraum ab:</label>'."\n";
	echo '				<select id="zeitraum_ab_m" name="zeitraum_ab_m" class="month">'."\n";

	if (!isset($_POST['zeitraum_ab_m'])) {
		$_POST['zeitraum_ab_m'] = date('m');
	}
	
	$i=1;
	while ($i < 13) {
		echo '						<option ';
		if (isset($_POST['zeitraum_ab_m'])) {
			if  ($i == $_POST['zeitraum_ab_m']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.$i.'">'.sprintf("%02.0f",$i).'</option>'."\n";
		$i++;
	}

	echo '				</select>&nbsp;/&nbsp;'."\n";
	echo '				<select name="zeitraum_ab_y" class="year">'."\n";

	$startyear = date('Y');
	$i = $startyear;
	while ($i < ($startyear + 4)) {
		echo '					<option ';
		if (isset($_POST['zeitraum_ab_y'])) {
			if  ($i == $_POST['zeitraum_ab_y']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.$i.'">'.sprintf("%01.0f",$i).'</option>'."\n";
		$i++;
	}

	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="zeitraum">Zeitraum Dauer:</label>'."\n";
	echo '				<input id="zeitraum" name="zeitraum" value="'.(isset($_POST['zeitraum']) ? $_POST['zeitraum'] : '').'" maxlength="100" />'."\n";
	echo '			</p>'."\n";

	if (isset($_POST['branche']) && !is_array($_POST['branche'])) {
		$_POST['branche'] = array();
	}
	$i=0;
	while ($i < $anz_branchen) {
		if ($i == 0) {
				echo '			<label for="branche'.$i.'">Branchenauswahl:</label>'."\n";
				echo '			<div class="col_2">'."\n";
		}
		
		$html = htmlspecialchars(mysql_result($branchen,$i,$_SESSION['s_sprache']));
		echo '				<p class="checkboxes">'."\n";
		echo '					<input type="checkbox" id="branche'.$i.'" name="branche[]" ';
		if (isset($_POST['branche'])) {
			if (in_array(mysql_result($branchen,$i,'id'),$_POST['branche'])) {
				echo 'checked="checked" ';
			}
		}
		echo 'value="'. mysql_result($branchen,$i,'id').'" />'."\n";
		echo '					<label for="branche'.$i.'">'.$html.'</label>'."\n";
		echo '				</p>'."\n";
		$i++;
	}

	echo '			</div>'."\n";
	echo '			<p style="clear: right; padding-top: 5px;">'."\n";
	echo '				<label for="beschreibungen"';

	if (isset($_POST['senden']) && empty($_POST['beschreibungen'])) {
		echo ' style="color: #ff0000;"';
	}

	echo '>Beschreibung Ihrer Praktikumsvorstellungen:</label>'."\n";
	echo '				<textarea id="beschreibungen" name="beschreibungen" cols="20" rows="6">'.htmlspecialchars((isset($_POST['beschreibungen']) ? $_POST['beschreibungen'] : '')).'</textarea>'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<h4>Ihre Person</h4>'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="qualifikation">Qualifikation:</label>'."\n";
	echo '				<select name="qualifikation" id="qualifikation">'."\n";

	$i=0;
	while ($i < $anz_qualifikationen) {
		$html = htmlspecialchars(mysql_result($qualifikationen,$i,'qualifikation'));
		echo '					<option ';
		if (isset($_POST['qualifikation'])) {
			if  (mysql_result($qualifikationen,$i,'id') == $_POST['qualifikation']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.mysql_result($qualifikationen,$i,'id').'">'.$html.'</option>'."\n";
		$i++;
	}
	
	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="sonst_qualifikation">sonstige Qualifikation:</label>'."\n";
	echo '				<input id="sonst_qualifikation" name="sonst_qualifikation" value="'.(isset($_POST['sonst_qualifikation']) ? $_POST['sonst_qualifikation'] : '').'" maxlength="200" />'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="umschulung">Besondere Kenntnisse:</label>'."\n";
	echo '				<textarea id="umschulung" name="umschulung" cols="20" rows="6">'.(isset($_POST['umschulung']) ? $_POST['umschulung'] : '').'</textarea>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="vorh_praktika">Vorherige Praktika:</label>'."\n";
	echo '				<textarea id="vorh_praktika" name="vorh_praktika" cols="20" rows="6">'.(isset($_POST['vorh_praktika']) ? $_POST['vorh_praktika'] : '').'</textarea>'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<h4>Regionale Einschr&auml;nkungen</h4>'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="studienort">Praktikumsort:</label>'."\n";
	echo '				<input id="studienort" name="studienort" value="'.(isset($_POST['studienort']) ? $_POST['studienort'] : '').'" maxlength="50" />'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<h4>Sprachen</h4>'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="sprachkenntnisse1">Sprachkenntnisse:</label>'."\n";
	echo '				<select name="sprachkenntnisse1" id="sprachkenntnisse1">'."\n";

	if (!isset($_POST['sprachkenntnisse1'])) {
		$_POST['sprachkenntnisse1'] = 2;
	}
	$i=0;
	while ($i < $anz_sprachen) {
		$html = htmlspecialchars(mysql_result($sprachen,$i,$_SESSION['s_sprache']));
		echo '					<option ';
		if (mysql_result($sprachen,$i,'id') == $_POST['sprachkenntnisse1']) {
			echo 'selected="selected" ';
		}
		echo 'value="'.mysql_result($sprachen,$i,'id').'">'.$html.'</option>'."\n";
		$i++;
	}
	
	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="sprachkenntnisse2">&nbsp;</label>'."\n";
	echo '				<select id="sprachkenntnisse2" name="sprachkenntnisse2">'."\n";

	$i=0;
	echo '					<option value="">--</option>'."\n";
	while ($i < $anz_sprachen) {
		$html = htmlspecialchars(mysql_result($sprachen,$i,$_SESSION['s_sprache']));
		echo '					<option ';
		if (isset($_POST['sprachkenntnisse2'])) {
			if (mysql_result($sprachen,$i,'id') == $_POST['sprachkenntnisse2']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.mysql_result($sprachen,$i,'id').'">'.$html.'</option>'."\n";
		$i++;
	}
	
	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="sprachkenntnisse3">&nbsp;</label>'."\n";
	echo '				<select id="sprachkenntnisse3" name="sprachkenntnisse3">'."\n";

	$i=0;
	echo '					<option value="">--</option>'."\n";
	while ($i < $anz_sprachen) {
		$html = htmlspecialchars(mysql_result($sprachen,$i,$_SESSION['s_sprache']));
		echo '					<option ';
		if (isset($_POST['sprachkenntnisse3'])) {
			if (mysql_result($sprachen,$i,'id') == $_POST['sprachkenntnisse3']) {
				echo 'selected="selected" ';
			}
		}
		echo 'value="'.mysql_result($sprachen,$i,'id').'">'.$html.'</option>'."\n";
		$i++;
	}
	
	echo '				</select>'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<h4>Verfall des Pratikumsgesuches</h4>'."\n";
	echo '		<fieldset>'."\n";
	echo '			<p>'."\n";
	echo '				<label for="verfall_tag">Verfallsdatum:</label>'."\n";

	if (empty($_POST['verfall_jahr'])) {
		$verfall_jahr = date('Y');
		$verfall_jahr++;
	} else {
		$verfall_jahr = $_POST['verfall_jahr'];
	}
	
	echo '				<input id="verfall_tag" name="verfall_tag" maxlength="2" value="'.((isset($_POST['verfall_tag']) && !empty($_POST['verfall_tag'])) ? $_POST['verfall_tag'] : date('d')).'" class="day" />.<input name="verfall_monat" maxlength="2" value="'.((isset($_POST['verfall_monat']) && !empty($_POST['verfall_monat'])) ? $_POST['verfall_monat'] : date('m')).'" class="month" />.<input name="verfall_jahr" maxlength="4" value="'.$verfall_jahr.'" class="year" />'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '		<fieldset class="control_panel">'."\n";
	echo '			<p>'."\n";
	echo '				<input type="hidden" id="gesuch" name="gesuch" value="'.(isset($_POST['gesuch']) ? $_POST['gesuch'] : '').'" />'."\n";
	echo '				<button type="submit" id="senden" name="senden" value="Speichern"><span><span><span>speichern</span></span></span></button>'."\n";
	echo '			</p>'."\n";
	echo '			<p>'."\n";
	echo '				<button type="button" name="back" onclick="location.href = \'/karriere/gesuche/\'" value="zur Gesuche&uuml;bersicht"><span><span><span>zur Gesuche&uuml;bersicht</span></span></span></button>'."\n";
	echo '			</p>'."\n";
	echo '		</fieldset>'."\n";
	echo '	</form>'."\n";
}
bodyoff();
?>