<?
require("/home/praktika/etc/config.inc.php");

if (!isset($_SESSION['s_loggedin']) || $_SESSION['s_loggedin'] == false) {
	header('Location: http://'.$_SERVER['HTTP_HOST'].'/login');
}

$_SESSION['restricted'] = RESTRICTED_CANDIDATE;
$_SESSION['current_user_group'] = USER_GROUP_CANDIDATES;
$_SESSION['current_page'] = PAGE_MY_PRAKTIKA;

if (isset($_GET['gesucheid'])) {
	$uebergabeteil = explode("-",$_GET['gesucheid']);
	
	if ($uebergabeteil[1] == 1) {
		$mystatsseite = '/karriere/gesuche/praktikum_detail/1/';
	} elseif ($uebergabeteil[1] == 2) {
		$mystatsseite = '/karriere/gesuche/diplom_detail/2/';
	} elseif ($uebergabeteil[1] == 3) {
		$mystatsseite = '/karriere/gesuche/berufseinstieg_detail/3/';
	} elseif ($uebergabeteil[1] == 4) {
		$mystatsseite = '/karriere/gesuche/nebenjob_detail/4/';
	} elseif ($uebergabeteil[1] == 5) {
		$mystatsseite = '/karriere/gesuche/ausbildung_detail/5/';
	}
}  else {
	$mystatsseite = '/karriere/gesuche/';
}

if (isset($_GET['B1'])) {
	header('Location: /karriere/gesuche/praktikum');
}

if (isset($_GET['B2']) && isset($_GET['gesucheid'])) {
	switch ($uebergabeteil[1]) {
		case 2:
			header('Location: /karriere/gesuche/diplom/'.$uebergabeteil[0].'/');
			break;

		case 3:
			header('Location: /karriere/gesuche/nebenjob/'.$uebergabeteil[0].'/');
			break;

		case 4:
			header('Location: /karriere/gesuche/ausbildung/'.$uebergabeteil[0].'/');
 			break;

		case 5:
			header('Location: /karriere/gesuche/berufseinstieg/'.$uebergabeteil[0].'/');
			break;

		default:
			header('Location: /karriere/gesuche/praktikum/'.$uebergabeteil[0].'/');
			break;
	}
} elseif (isset($_GET['B2'])) {
	header('Location: '.$mystatsseite);
}

if (isset($_GET['B3']) && isset($_GET['gesucheid'])) {
	header('Location: '.$mystatsseite.$uebergabeteil[0].'/');
} elseif (isset($_GET['B3'])) {
	header('Location: '.$mystatsseite);
}

if (isset($_GET['B4']) && isset($_GET['gesucheid'])) {
	$idgesuch = $uebergabeteil[0];
	switch ($uebergabeteil[1]) {
		case 2:
			$results = mysql_db_query($database_db,'DELETE FROM diplomgesuch WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			 break;

		case 3:
			$results = mysql_db_query($database_db,'DELETE FROM nebenjobgesuch WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			break;

		case 4:
			$results = mysql_db_query($database_db,'DELETE FROM ausbildungsgesuch WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			break;
 		
		case 5:
			$results = mysql_db_query($database_db,'DELETE FROM berufseinstieggesuch WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			break;
 		
		default:
			$results = mysql_db_query($database_db,'DELETE FROM praktikanten WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			break;
	}
} elseif (isset($_GET['B4'])) {
	header('Location: '.$mystatsseite);
}

if (isset($_GET['B5']) && isset($_GET['gesucheid'])) {
	$idgesuch = $uebergabeteil[0];
	switch ($uebergabeteil[1]) {
		case 2:
		 	$results = mysql_db_query($database_db,'UPDATE diplomgesuch set inactive=\'false\' WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			break;
 		case 3:
 			$results = mysql_db_query($database_db,'UPDATE nebenjobgesuch set inactive=\'false\' WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			break;
 		case 4:
		 	$results = mysql_db_query($database_db,'UPDATE ausbildungsgesuch set inactive=\'false\' WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			break;
 		case 5:
		 	$results = mysql_db_query($database_db,'UPDATE berufseinstieggesuch set inactive=\'false\' WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			break;
 		default:
		 	$results = mysql_db_query($database_db,'UPDATE praktikanten set inactive=\'false\' WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			break;
	}
} elseif (isset($_GET['B5'])) {
	header('Location: '.$mystatsseite);
}

if (isset($_GET['B6']) && isset($_GET['gesucheid'])) {
	$idgesuch = $uebergabeteil[0];
	switch ($uebergabeteil[1]) {
		case 2:
	 		$results = mysql_db_query($database_db,'UPDATE diplomgesuch set inactive=\'true\' WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			break;
 		case 3:
 			$results = mysql_db_query($database_db,'UPDATE nebenjobgesuch set inactive=\'true\' WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			break;
 		case 4:
 			$results = mysql_db_query($database_db,'UPDATE ausbildungsgesuch set inactive=\'true\' WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			break;
 		case 5:
 			$results = mysql_db_query($database_db,'UPDATE berufseinstieggesuch set inactive=\'true\' WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			break;
 		default:
 			$results = mysql_db_query($database_db,'UPDATE praktikanten set inactive=\'true\' WHERE nutzerid='.$_SESSION['s_loginid'].' AND id='.$idgesuch,$praktdbmaster);
			break;
	}
} elseif (isset($_GET['B6'])) {
	header('Location: '.$mystatsseite);
}

if (isset($_GET['B7']) && isset($_GET['gesucheid'])) {
	header('Location: /karriere/gesuche/vorschau/'.$uebergabeteil[0].'/'.$uebergabeteil[1].'/');
}



//echo helpsystem(543242,41,'Gesuche Tipps &amp; Hilfe');

$results1 = mysql_db_query($database_db,'SELECT id,inactive,taetigkeit,datum_eintrag FROM praktikanten WHERE nutzerid='.$_SESSION['s_loginid'].'',$praktdbmaster);
$results2 = mysql_db_query($database_db,'SELECT id,inactive,titel as taetigkeit FROM diplomgesuch WHERE nutzerid='.$_SESSION['s_loginid'].'',$praktdbmaster);
$results3 = mysql_db_query($database_db,'SELECT id,inactive,taetigkeit,datum_eintrag FROM nebenjobgesuch WHERE nutzerid='.$_SESSION['s_loginid'].'',$praktdbmaster);
$results4 = mysql_db_query($database_db,'SELECT id,inactive,taetigkeit,datum_eintrag FROM ausbildungsgesuch WHERE nutzerid='.$_SESSION['s_loginid'].'',$praktdbmaster);
$results5 = mysql_db_query($database_db,'SELECT id,inactive,bezeichnung as taetigkeit,datum_eintrag FROM berufseinstieggesuch WHERE nutzerid='.$_SESSION['s_loginid'].'',$praktdbmaster);

$gesuchearray = array();
$i = 0;
while ($result_row = mysql_fetch_array($results1)) {
	$gesuchearray[$i] = $result_row;
	$gesuchearray[$i][] = 1;
	$gesuchearray[$i]['spalte'] = SECTION_PRAKTIKUM;
	$gesuchearray[$i]['spalte_alpha'] = SECTION_PRAKTIKUM_ALPHA;
	$i++;
}
while ($result_row = mysql_fetch_array($results2)) {
	$gesuchearray[$i] = $result_row;
	$gesuchearray[$i][] = 2;
	$gesuchearray[$i]['spalte'] = SECTION_DIPLOM;
	$gesuchearray[$i]['spalte_alpha'] = SECTION_DIPLOM_ALPHA;
	$i++;
}
while ($result_row = mysql_fetch_array($results3)) {
	$gesuchearray[$i] = $result_row;
	$gesuchearray[$i][] = 3;
	$gesuchearray[$i]['spalte'] = SECTION_NEBENJOB;
	$gesuchearray[$i]['spalte_alpha'] = SECTION_NEBENJOB_ALPHA;
	$i++;
}
while ($result_row = mysql_fetch_array($results4)) {
	$gesuchearray[$i] = $result_row;
	$gesuchearray[$i][] = 4;
	$gesuchearray[$i]['spalte'] = SECTION_AUSBILDUNG;
	$gesuchearray[$i]['spalte_alpha'] = SECTION_AUSBILDUNG_ALPHA;
	$i++;
}
while ($result_row = mysql_fetch_array($results5)) {
	$gesuchearray[$i] = $result_row;
	$gesuchearray[$i][] = 5;
	$gesuchearray[$i]['spalte'] = SECTION_BERUFSEINSTIEG;
	$gesuchearray[$i]['spalte_alpha'] = SECTION_BERUFSEINSTIEG_ALPHA;
	$i++;
}
if (count($gesuchearray)>0) {
	$bereichsortierung = 'spalte';
	$gesuchearray = array_csort($gesuchearray,$bereichsortierung,SORT_ASC);
}
reset($gesuchearray);

if (isset($gesuchearray) && !empty($gesuchearray)) {
	pageheader(array('page_title' => 'Gesuche verwalten'));
	echo '<form name="agentform" method="get" action="/karriere/gesuche/">'."\n";
	echo '	<h4>Liste Ihrer Gesuche</h4>'."\n";
	echo '	<fieldset>'."\n";
	echo '		<p>'."\n";
	echo '			<select name="gesucheid" size="8" style="width: 380px; float: left;">'."\n";
	           
	$i=0;
	while (current($gesuchearray)) {
		$result_row = $gesuchearray[$i];
		echo '				<option ';
		if ($result_row['inactive'] == 'false') {
			echo 'style="color: rgb(0,100,0)" ';
			$status = ' - [AKTIVIERT]';
		} else {
			echo 'style="color: rgb(255,0,0)" ';
			$status = ' - [DEAKTIVIERT]';
		}
		/*if ($result_row['id'] == $agentid) {
			echo 'selected="selected" ';
		}*/
		echo 'value="'.$result_row['id'].'-'.$result_row['spalte'].'">';
		echo $result_row['spalte_alpha'].' - ';
		if (strlen($result_row['taetigkeit']) > 30) {
			echo substr($result_row['taetigkeit'],0,28).'...';
		} else {
			echo $result_row['taetigkeit'];
		}
		echo $status.'</option>'."\n";
		next($gesuchearray);
		$i++;
	}
	
	echo '			</select>'."\n";
	echo '		</p>'."\n";
	echo '		<p class="gesuche_inputs">'."\n";
	echo '			<button type="submit" name="B1" value="Neu"><span><span><span>Neu</span></span></span></button>'."\n";
	echo '			<button type="submit" name="B2" value="Bearbeiten" onclick="return CheckInput();"><span><span><span>Bearbeiten</span></span></span></button>'."\n";
	echo '			<button type="submit" name="B7" value="Vorschau" onclick="return CheckInput();"><span><span><span>Vorschau</span></span></span></button>'."\n";
	echo '			<button type="submit" name="B3" value="Statistik" onclick="return CheckInput();"><span><span><span>Statistik</span></span></span></button>'."\n";
	echo '			<button type="submit" name="B4" value="L&ouml;schen" onclick="return CheckInput();"><span><span><span>L&ouml;schen</span></span></span></button>'."\n";
	echo '			<button type="submit" name="B5" value="Aktivieren" class="green" onclick="return CheckInput();"><span><span><span>Aktivieren</span></span></span></button>'."\n";
	echo '			<button type="submit" name="B6" value="Deaktivieren" class="lightred" onclick="return CheckInput();"><span><span><span>Deaktivieren</span></span></span></button>'."\n";
	echo '			<button type="button" name="back" value="zur&uuml;ck" onclick="location.href = \'/karriere/account/\'"><span><span><span>zur&uuml;ck</span></span></span></button>'."\n";
	echo '		</p>'."\n";
	echo '	</fieldset>'."\n";
	echo '</form>'."\n";
	?>
	<script type="text/javascript">
	/* <![CDATA[ */
	function CheckInput(knopf) {
		if (document.agentform.gesucheid.selectedIndex == -1) {
			alert('Bitte wählen Sie zuerst eine Gesuch aus!');
			return false;
		} else {
			if (knopf == 'B4') {
				return confirm('Wollen Sie dieses Gesuch wirklich löschen?');
			} else {
				return true;
			}
		}
	}
	/* ]]> */
	</script>
	<?php
} else {
	header('Location: /karriere/gesuche/praktikum/');
}
bodyoff();
?>