<?
header("Location: /suche/".$_GET["suchstring"]);
exit();
 $spalte = 1;
 $gruppe = "praktikanten";
 $sprachbasisdatei="/home/praktikanten/volltext.phtml"; 
 require("/home/praktika/etc/config.inc.php"); 
 require("/home/praktika/etc/firmensuche.inc.php"); 
 require("/home/praktika/etc/suchlogging.inc.php"); 

if ($decode=="true") $suchstring=urldecode($suchstring);

pageheader(session_id(), session_name()); ?>
      <table width="90%">
        <tr> 
          <td><h1 class="layout1">Suchergebnis Volltextsuche</h1>
              <? 

mysql_select_db ($database_db,$praktdbslave);

/* Counter Statistik der Suche */
$modify = date("YmdHis");
$updatestring = "UPDATE statseinblick SET modify='$modify',counter=counter+1 WHERE id=1";
mysql($database_db,$updatestring,$praktdbmaster);
/* Counter Statistik der Suche Ende */

//$suchstring=trim(str_replace("\"","",stripslashes($suchstring)));
//if ($suchstring == "" || substr_count($suchstring,"@") <4 {
if ($suchstring == "") {
?>
            <table width="100%">
              <tr> 
                <td> <? echo $language ["strAnfrage"]; ?>
                  <p>&nbsp;</p>
                  <form action="">
                    <hr>
                    <input type="BUTTON" value="<? echo $language ["strZSuchseite"]; ?>" onClick="location.replace('einblick.phtml?suchwahl=volltext')">
                    <hr>
                  </form>
                </td>
              </tr>
            </table>
<?
} else {

$s_suchstring=$suchstring;
echo "<strong>Suchbegriff: ".htmlspecialchars($suchstring)."</strong>";
?>

              <table width="100%">
              <tr>
                <td align="right"><a href="/home/praktikanten/jobmail/config.phtml?neu=YES&amp;<? echo "rubrick=volltext&amp;auswahl=".urlencode($suchstring)."&amp;agname=Volltextsuche"; ?>">Diese Suche speichern</a> 
                </td>
              </tr>
            </table><br>


<?
if (!isset($ds_count) && !isset($seite)) insert_suche($suchstring,"Praktikum");

// uebergabevariablen konvertieren //
$ds_count = intval( $ds_count);
$ds_pro_seite = intval( $ds_pro_seite);

// abfrage ausfuehren (inactive <> true ) //

$sucharray = explode(" ",$suchstring);
foreach ($sucharray as $suchvalpart) {
	if ($suchvalpart{0} != "+" && $suchvalpart{0} != "-" && $suchvalpart{0} != "~"  && $suchvalpart{0} != "*")
		$suchvalpart = "+".$suchvalpart;
	$sucharrayfinal[] = $suchvalpart;
}
	
$suchstringfinal = implode(" ", $sucharrayfinal);

/*
$query = "SELECT t1.id AS firmenid, t2.id, t1.searchtop, t1.firma, t1.strasse, t1.ort, t1.plz, t1.bundesland, t2.einsatzort, t1.grossraum, t1.land, t3.german, t1.branche, t2.taetigkeit, t2.zeitraum_von, t2.zeitraum_bis, date_format( t2.zeitraum_von, '%Y' ) AS jahrvon, date_format( t2.zeitraum_bis, '%Y' ) AS jahrbis, t2.zeitraum, t2.schuelerprakt, t2.hochschulprakt, t2.wprakt, t2.sonstprakt,
		  MATCH (t2.beschreibung,t2.taetigkeit,t2.stichwort,t2.einsatzort,t1.firma,t1.ort) AGAINST ('$suchstring') AS ranking 
		  FROM praktikumsstellen AS t2 
		  LEFT JOIN firmen AS t1 ON ( t2.firmenid = t1.id )
		  LEFT JOIN land AS t3 ON ( t3.id = t1.land )
		  WHERE (t2.inactive <> 'true') AND (t1.inactive <> 'true') AND (t1.land <>0) AND
		  MATCH (t2.beschreibung, t2.taetigkeit, t2.stichwort, t1.firma, t1.ort, t2.einsatzort)
		  AGAINST ('$suchstring'IN BOOLEAN MODE)
		  ORDER BY t1.searchtop DESC, t2.modify DESC";
*/


$query = "SELECT t1.id AS firmenid, t2.id,t1.searchtop,t1.firma,t1.strasse,t1.ort,t1.plz,t1.bundesland,t2.einsatzort,t2.einsatzgrossraum,t2.einsatzland,t3.german,t1.branche,t2.taetigkeit,t2.zeitraum_von,t2.zeitraum_bis,date_format(t2.zeitraum_von, '%Y') as jahrvon,date_format(t2.zeitraum_bis, '%Y') as jahrbis,t2.zeitraum,t2.schuelerprakt,t2.hochschulprakt,t2.wprakt,t2.sonstprakt, MATCH (t2.beschreibung) AGAINST ('$suchstringfinal')as ranking FROM firmen AS t1, praktikumsstellen AS t2, land AS t3 WHERE (t2.inactive <> 'true') AND (t1.inactive <> 'true') AND (t2.firmenid = t1.id) AND (t3.id = t1.land) AND (t1.land <> 0) AND MATCH (t2.beschreibung,t2.taetigkeit,t2.stichwort,t2.einsatzort,t1.firma,t1.ort) AGAINST ('$suchstringfinal' IN BOOLEAN MODE) ORDER BY t1.searchtop ASC, t2.modify DESC, ranking DESC";

if ($s_debug == "yes") echo $query;

$results = mysql($database_db,$query,$praktdbslave);

// datensaetze gefunden ? //
$num_rows = mysql_num_rows( $results );

if (!$ds_count && !$seite && $num_rows > 0) {
echo "<iframe id=\"geodata\" name=\"geodata\" src=\"/home/praktikanten/geodata.phtml?".session_name()."=".session_id()."\" width=\"450\" height=\"380\" marginwidth=\"0\" marginheight=\"0\" style=\"margin:0px\" frameborder=\"no\" scrolling=\"auto\">Ihr Browser kann leider keine eingebetteten Frames anzeigen</iframe>";
}

if ( $num_rows  > 0) {

$geldsuche = "no";
$rueckgabe = suchergebnis($results,$ds_count,$ds_pro_seite,$num_rows,$geldsuche);

$ds_value=($ds_count);
$ds_count = $rueckgabe[0];
$ds_pro_seite = $rueckgabe[1];

		if ((!$ds_start || $ds_start == 0) && !$seite) {		
			if (!$s_lastresult) session_register("s_lastresult");
			$s_lastresult = array();
			mysql_data_seek( $results, 0 );
			$lastresultzaehler = 0;
			$s_lastresult="";
			while ( ($lastresultzaehler < 100) &&  ($lastresult_row = mysql_fetch_array ( $results )) ) {
				$s_lastresult["werte"][$lastresult_row["id"]]["stellenid"] = $lastresult_row["id"];
				$s_lastresult["werte"][$lastresult_row["id"]]["firmenid"] = $lastresult_row["firmenid"];
				$s_lastresult["werte"][$lastresult_row["id"]]["firma"] = $lastresult_row["firma"];
				$s_lastresult["werte"][$lastresult_row["id"]]["taetigkeit"] = $lastresult_row["taetigkeit"];
				if ($lastresult_row["einsatzort"]) {
					$s_lastresult["werte"][$lastresult_row["id"]]["ort"] = $lastresult_row["einsatzort"];
				} else {
					$s_lastresult["werte"][$lastresult_row["id"]]["ort"] = $lastresult_row["ort"];
				}
				$s_lastresult["werte"][$lastresult_row["id"]]["land"] = $lastresult_row["einsatzland"];
				$s_lastresult["orte"][$lastresult_row["einsatzland"]][] = $s_lastresult["werte"][$lastresult_row["id"]]["ort"];
				$lastresultzaehler++;
			}
		}


mysql_Free_Result( $results ); ?> 
              <hr>
              <table width="100%">
                <tr> 
                  <td align="left"> 
                  <? if ($ds_count > $ds_pro_seite) { ?> 
                    <form action="<? echo $PHP_SELF; ?>" method="get">
                      <input type="hidden" name="<? echo session_name() ?>" value="<? echo session_id() ?>">
                      <input type="HIDDEN" name="ds_count" value="<? echo ($ds_value-$ds_pro_seite); ?>">
                      <input type="HIDDEN" name="suchstring" value="<? echo urldecode($suchstring); ?>">
                      <input type="HIDDEN" name="ds_count" value="<? echo ($ds_value-$ds_pro_seite); ?>">
                      <input type="HIDDEN" name="ds_value" value="<? echo $ds_value ?>">
                      <input type="HIDDEN" name="ds_pro_seite" value="<? echo $ds_pro_seite ?>">
                      <input type="SUBMIT" value="<? echo $language ["strZurueck"]; ?>">
                    </form><? } else {?>

                    <form action="">
                    <input type="BUTTON" value="<? echo $language ["strZSuchseite"]; ?>" onClick="location.replace('einblick.phtml?suchwahl=volltext')">
                    </form> <? } ?>
                  </td>
                  <? if ($ds_count < $num_rows) { ?> 
                  <td align="right"> 
                    <form action="<? echo $PHP_SELF; ?>" method="get">
                      <input type="hidden" name="<? echo session_name() ?>" value="<? echo session_id() ?>">
                      <input type="HIDDEN" name="suchstring" <?php echo "value=\"".urldecode($suchstring)."\""; ?> >
                      <input type="HIDDEN" name="ds_value" value=<? echo $ds_value ?>>
                      <input type="HIDDEN" name="ds_count" value=<? echo $ds_count ?>>
                      <input type="HIDDEN" name="ds_pro_seite" value=<? echo $ds_pro_seite ?>>
                      <input type="SUBMIT" value="<? echo $language ["strZNaechsten"]; ?><? echo min( $ds_pro_seite, ($num_rows - $ds_count) ) ?> <? echo $language ["strErgebnisse"]; ?> &gt;">
                    </form>
                  </td>
                  <? }
                  if ($ds_count == $num_rows && $ds_count > 5) { ?>
                  <td align="right"> 
                  <form action="">
                    <input type="BUTTON" value="<? echo $language ["strZSuchseite"]; ?>" onClick="location.replace('einblick.phtml?suchwahl=volltext')">
                  </form>
                  </td> <? } ?> </tr>
              </table>
              <hr>
              <? } else { ?> 
              <table width="100%">
              <tr> 
                <td> <? echo $language ["strKDS"]; ?> 
                  <p>&nbsp;</p>
                  <form action="">
                    <input type="BUTTON" value="<? echo $language ["strZSuchseite"]; ?>" onClick="location.replace('einblick.phtml?suchwahl=volltext')">
                  </form>
            <? }} ?> </td>
        </tr>
      </table>
<? bodyoff(session_id(), session_name()); ?>
